'use strict';

/* Quiz -- tema "ciencia". Cada pergunta: id estavel, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  const dados = [
    [1, 0,
      ['Qual planeta é conhecido como planeta vermelho?',
        'Marte|Vênus|Júpiter|Mercúrio'],
      ['Which planet is known as the Red Planet?',
        'Mars|Venus|Jupiter|Mercury'],
      ['¿Qué planeta es conocido como el planeta rojo?',
        'Marte|Venus|Júpiter|Mercurio']],
    [1, 1,
      ['Qual gás as plantas absorvem na fotossíntese?',
        'Oxigênio|Dióxido de carbono|Nitrogênio|Hélio'],
      ['Which gas do plants absorb during photosynthesis?',
        'Oxygen|Carbon dioxide|Nitrogen|Helium'],
      ['¿Qué gas absorben las plantas durante la fotosíntesis?',
        'Oxígeno|Dióxido de carbono|Nitrógeno|Helio']],
    [1, 2,
      ['Qual órgão bombeia o sangue pelo corpo?',
        'Pulmão|Fígado|Coração|Rim'],
      ['Which organ pumps blood through the body?',
        'Lung|Liver|Heart|Kidney'],
      ['¿Qué órgano bombea la sangre por el cuerpo?',
        'Pulmón|Hígado|Corazón|Riñón']],
    [1, 3,
      ['Qual é a estrela no centro do Sistema Solar?',
        'Sírius|Polaris|Betelgeuse|Sol'],
      ['What is the star at the center of the Solar System?',
        'Sirius|Polaris|Betelgeuse|Sun'],
      ['¿Cuál es la estrella en el centro del Sistema Solar?',
        'Sirio|Polar|Betelgeuse|Sol']],
    [1, 0,
      ['Qual linguagem é usada para estilizar páginas web?',
        'CSS|SQL|Java|C++'],
      ['Which language is used to style web pages?',
        'CSS|SQL|Java|C++'],
      ['¿Qué lenguaje se usa para dar estilo a las páginas web?',
        'CSS|SQL|Java|C++']],
    [1, 1,
      ['Qual planeta é o maior do Sistema Solar?',
        'Saturno|Júpiter|Netuno|Urano'],
      ['Which planet is the largest in the Solar System?',
        'Saturn|Jupiter|Neptune|Uranus'],
      ['¿Cuál planeta es el más grande del Sistema Solar?',
        'Saturno|Júpiter|Neptuno|Urano']],
    [1, 2,
      ['Qual destes é um navegador de internet?',
        'Word|Excel|Firefox|Photoshop'],
      ['Which of these is a web browser?',
        'Word|Excel|Firefox|Photoshop'],
      ['¿Cuál de estos es un navegador de internet?',
        'Word|Excel|Firefox|Photoshop']],
    [1, 3,
      ['Quem criou a prensa de tipos móveis na Europa do século XV?',
        'Leonardo da Vinci|Isaac Newton|Thomas Edison|Johannes Gutenberg'],
      ['Who created the movable-type printing press in 15th-century Europe?',
        'Leonardo da Vinci|Isaac Newton|Thomas Edison|Johannes Gutenberg'],
      ['¿Quién creó la imprenta de tipos móviles en la Europa del siglo XV?',
        'Leonardo da Vinci|Isaac Newton|Thomas Edison|Johannes Gutenberg']],
    [1, 0,
      ['Qual é o símbolo químico do ouro?',
        'Au|Ag|Fe|O'],
      ['What is the chemical symbol for gold?',
        'Au|Ag|Fe|O'],
      ['¿Cuál es el símbolo químico del oro?',
        'Au|Ag|Fe|O']],
    [1, 1,
      ['Qual gás é mais abundante na atmosfera da Terra?',
        'Oxigênio|Nitrogênio|Dióxido de carbono|Argônio'],
      ["Which gas is most abundant in Earth's atmosphere?", 'Oxygen|Nitrogen|Carbon dioxide|Argon'],
      ['¿Qué gas es más abundante en la atmósfera de la Tierra?',
        'Oxígeno|Nitrógeno|Dióxido de carbono|Argón']],
    [1, 2,
      ['Qual é o satélite natural da Terra?',
        'Europa|Titã|Lua|Fobos'],
      ["What is Earth's natural satellite?", 'Europa|Titan|Moon|Phobos'],
      ['¿Cuál es el satélite natural de la Tierra?',
        'Europa|Titán|Luna|Fobos']],
    [1, 3,
      ['Qual vitamina o corpo pode produzir com exposição à luz solar?',
        'Vitamina A|Vitamina B12|Vitamina C|Vitamina D'],
      ['Which vitamin can the body produce with exposure to sunlight?',
        'Vitamin A|Vitamin B12|Vitamin C|Vitamin D'],
      ['¿Qué vitamina puede producir el cuerpo con exposición a la luz solar?',
        'Vitamina A|Vitamina B12|Vitamina C|Vitamina D']],
    [1, 0,
      ['O que significa a sigla CPU?',
        'Unidade Central de Processamento|Unidade de Cache Principal|Usuário Central de Programas|'
        + 'Unidade Combinada de Pixels'],
      ['What does the acronym CPU stand for?',
        'Central Processing Unit|Main Cache Unit|Central Program User|Combined Pixel Unit'],
      ['¿Qué significa la sigla CPU?',
        'Unidad Central de Procesamiento|Unidad de Caché Principal|Usuario Central de Programas|'
        + 'Unidad Combinada de Píxeles']],
    [1, 1,
      ['O "e" de e-mail vem de qual palavra?',
        'Escrito|Eletrônico|Expresso|Externo'],
      ['The "e" in e-mail comes from which word?',
        'Written|Electronic|Express|External'],
      ['¿De qué palabra viene la "e" de e-mail?',
        'Escrito|Electrónico|Exprés|Externo']],
    [1, 2,
      ['Qual planeta fica mais perto do Sol?',
        'Vênus|Terra|Mercúrio|Marte'],
      ['Which planet is closest to the Sun?',
        'Venus|Earth|Mercury|Mars'],
      ['¿Qué planeta está más cerca del Sol?',
        'Venus|Tierra|Mercurio|Marte']],
    [1, 3,
      ['Que metal é líquido em temperatura ambiente?',
        'Ferro|Alumínio|Cobre|Mercúrio'],
      ['Which metal is liquid at room temperature?',
        'Iron|Aluminum|Copper|Mercury'],
      ['¿Qué metal es líquido a temperatura ambiente?',
        'Hierro|Aluminio|Cobre|Mercurio']],
    [1, 0,
      ['Qual estrutura celular contém o material genético?',
        'Núcleo|Parede celular|Ribossomo|Membrana celular'],
      ['Which cell structure contains genetic material?',
        'Nucleus|Cell wall|Ribosome|Cell membrane'],
      ['¿Qué estructura celular contiene material genético?',
        'Núcleo|Pared celular|Ribosoma|Membrana celular']],
    [1, 1,
      ['Quantas pernas tem um inseto?',
        'Quatro|Seis|Oito|Dez'],
      ['How many legs does an insect have?',
        'Four|Six|Eight|Ten'],
      ['¿Cuántas patas tiene un insecto?',
        'Cuatro|Seis|Ocho|Diez']],
    [1, 2,
      ['Qual é o processo pelo qual uma lagarta se torna borboleta?',
        'Germinação|Fermentação|Metamorfose|Evaporação'],
      ['What is the process by which a caterpillar becomes a butterfly?',
        'Germination|Fermentation|Metamorphosis|Evaporation'],
      ['¿Cuál es el proceso por el que una oruga se convierte en mariposa?',
        'Germinación|Fermentación|Metamorfosis|Evaporación']],
    [1, 3,
      ['Qual camada protege a Terra de grande parte da radiação ultravioleta do Sol?',
        'Troposfera|Ionosfera|Magnetosfera|Camada de ozônio'],
      ["Which layer protects Earth from much of the Sun's ultraviolet radiation?",
        'Troposphere|Ionosphere|Magnetosphere|Ozone layer'],
      ['¿Qué capa protege a la Tierra de gran parte de la radiación ultravioleta del Sol?',
        'Troposfera|Ionosfera|Magnetosfera|Capa de ozono']],
    [2, 0,
      ['Quem descobriu a penicilina?',
        'Alexander Fleming|Louis Pasteur|Robert Koch|Jonas Salk'],
      ['Who discovered penicillin?',
        'Alexander Fleming|Louis Pasteur|Robert Koch|Jonas Salk'],
      ['¿Quién descubrió la penicilina?',
        'Alexander Fleming|Louis Pasteur|Robert Koch|Jonas Salk']],
    [2, 1,
      ['Qual elemento tem número atômico 1?',
        'Hélio|Hidrogênio|Lítio|Carbono'],
      ['Which element has atomic number 1?',
        'Helium|Hydrogen|Lithium|Carbon'],
      ['¿Qué elemento tiene número atómico 1?',
        'Helio|Hidrógeno|Litio|Carbono']],
    [2, 2,
      ['Quem propôs a World Wide Web em 1989?',
        'Vint Cerf|Bill Gates|Tim Berners-Lee|Steve Jobs'],
      ['Who proposed the World Wide Web in 1989?',
        'Vint Cerf|Bill Gates|Tim Berners-Lee|Steve Jobs'],
      ['¿Quién propuso la World Wide Web en 1989?',
        'Vint Cerf|Bill Gates|Tim Berners-Lee|Steve Jobs']],
    [2, 3,
      ['Qual força mantém os planetas em órbita ao redor do Sol?',
        'Eletricidade|Magnetismo|Atrito|Gravidade'],
      ['Which force keeps planets in orbit around the Sun?',
        'Electricity|Magnetism|Friction|Gravity'],
      ['¿Qué fuerza mantiene a los planetas en órbita alrededor del Sol?',
        'Electricidad|Magnetismo|Fricción|Gravedad']],
    [2, 0,
      ['Qual cientista formulou as três leis do movimento?',
        'Isaac Newton|Galileu Galilei|Johannes Kepler|Nikola Tesla'],
      ['Which scientist formulated the three laws of motion?',
        'Isaac Newton|Galileo Galilei|Johannes Kepler|Nikola Tesla'],
      ['¿Qué científico formuló las tres leyes del movimiento?',
        'Isaac Newton|Galileo Galilei|Johannes Kepler|Nikola Tesla']],
    [2, 1,
      ['Qual é a unidade básica da corrente elétrica?',
        'Volt|Ampere|Watt|Ohm'],
      ['What is the basic unit of electric current?',
        'Volt|Ampere|Watt|Ohm'],
      ['¿Cuál es la unidad básica de la corriente eléctrica?',
        'Voltio|Amperio|Vatio|Ohmio']],
    [2, 2,
      ['Que tipo de rocha se forma pelo resfriamento de material derretido?',
        'Sedimentar|Metamórfica|Ígnea|Calcária'],
      ['Which type of rock forms from cooled molten material?',
        'Sedimentary|Metamorphic|Igneous|Limestone'],
      ['¿Qué tipo de roca se forma al enfriarse material fundido?',
        'Sedimentaria|Metamórfica|Ígnea|Caliza']],
    [2, 3,
      ['Qual parte do ouvido interno ajuda a manter o equilíbrio?',
        'Cóclea|Tímpano|Ossículos|Canais semicirculares'],
      ['Which part of the inner ear helps maintain balance?',
        'Cochlea|Eardrum|Ossicles|Semicircular canals'],
      ['¿Qué parte del oído interno ayuda a mantener el equilibrio?',
        'Cóclea|Tímpano|Huesecillos|Canales semicirculares']],
    [2, 0,
      ['Qual é o processo de divisão celular que produz gametas?',
        'Meiose|Mitose|Fusão|Clonagem'],
      ['What is the cell division process that produces gametes?',
        'Meiosis|Mitosis|Fusion|Cloning'],
      ['¿Cuál es el proceso de división celular que produce gametos?',
        'Meiosis|Mitosis|Fusión|Clonación']],
    [2, 1,
      ['Qual é o nome da galáxia que contém o Sistema Solar?',
        'Andrômeda|Via Láctea|Triângulo|Sombreiro'],
      ['What is the name of the galaxy that contains the Solar System?',
        'Andromeda|Milky Way|Triangulum|Sombrero'],
      ['¿Cuál es el nombre de la galaxia que contiene el Sistema Solar?',
        'Andrómeda|Vía Láctea|Triángulo|Sombrero']],
    [2, 2,
      ['Qual cientista ganhou o Prêmio Nobel de Física e o de Química?',
        'Rosalind Franklin|Ada Lovelace|Marie Curie|Lise Meitner'],
      ['Which scientist won both the Nobel Prize in Physics and in Chemistry?',
        'Rosalind Franklin|Ada Lovelace|Marie Curie|Lise Meitner'],
      ['¿Qué científica ganó el Premio Nobel de Física y el de Química?',
        'Rosalind Franklin|Ada Lovelace|Marie Curie|Lise Meitner']],
    [2, 3,
      ['Qual cientista é associado à teoria da relatividade?',
        'Charles Darwin|Gregor Mendel|Max Planck|Albert Einstein'],
      ['Which scientist is associated with the theory of relativity?',
        'Charles Darwin|Gregor Mendel|Max Planck|Albert Einstein'],
      ['¿Qué científico está asociado con la teoría de la relatividad?',
        'Charles Darwin|Gregor Mendel|Max Planck|Albert Einstein']],
    [2, 0,
      ['Qual partícula subatômica tem carga negativa?',
        'Elétron|Próton|Nêutron|Núcleo'],
      ['Which subatomic particle has a negative charge?',
        'Electron|Proton|Neutron|Nucleus'],
      ['¿Qué partícula subatómica tiene carga negativa?',
        'Electrón|Protón|Neutrón|Núcleo']],
    [2, 1,
      ['Qual camada da Terra é formada principalmente por ferro e níquel?',
        'Manto|Núcleo|Crosta|Litosfera'],
      ["Which layer of Earth is made mostly of iron and nickel?", 'Mantle|Core|Crust|Lithosphere'],
      ['¿Qué capa de la Tierra está formada principalmente por hierro y níquel?',
        'Manto|Núcleo|Corteza|Litosfera']],
    [2, 2,
      ['Qual é o pH aproximado da água pura a 25 °C?',
        '2|5|7|10'],
      ['What is the approximate pH of pure water at 25 °C?',
        '2|5|7|10'],
      ['¿Cuál es el pH aproximado del agua pura a 25 °C?',
        '2|5|7|10']],
    [2, 3,
      ['Qual é a menor unidade de informação em computação?',
        'Byte|Pixel|Hertz|Bit'],
      ['What is the smallest unit of information in computing?',
        'Byte|Pixel|Hertz|Bit'],
      ['¿Cuál es la unidad mínima de información en computación?',
        'Byte|Píxel|Hercio|Bit']],
    [2, 0,
      ['Qual órgão produz a insulina?',
        'Pâncreas|Baço|Vesícula biliar|Tireoide'],
      ['Which organ produces insulin?',
        'Pancreas|Spleen|Gallbladder|Thyroid'],
      ['¿Qué órgano produce insulina?',
        'Páncreas|Bazo|Vesícula biliar|Tiroides']],
    [2, 1,
      ['Qual planeta possui os anéis mais visíveis do Sistema Solar?',
        'Júpiter|Saturno|Urano|Netuno'],
      ['Which planet has the most visible rings in the Solar System?',
        'Jupiter|Saturn|Uranus|Neptune'],
      ['¿Qué planeta tiene los anillos más visibles del Sistema Solar?',
        'Júpiter|Saturno|Urano|Neptuno']],
    [2, 2,
      ['Quem desenvolveu a vacina contra a raiva?',
        'Edward Jenner|Robert Koch|Louis Pasteur|Joseph Lister'],
      ['Who developed a vaccine against rabies?',
        'Edward Jenner|Robert Koch|Louis Pasteur|Joseph Lister'],
      ['¿Quién desarrolló una vacuna contra la rabia?',
        'Edward Jenner|Robert Koch|Louis Pasteur|Joseph Lister']],
    [2, 3,
      ['Qual molécula transporta oxigênio no sangue?',
        'Queratina|Colágeno|Insulina|Hemoglobina'],
      ['Which molecule transports oxygen in the blood?',
        'Keratin|Collagen|Insulin|Hemoglobin'],
      ['¿Qué molécula transporta oxígeno en la sangre?',
        'Queratina|Colágeno|Insulina|Hemoglobina']],
    [2, 0,
      ['Qual é o principal componente do gás natural?',
        'Metano|Etano|Propano|Butano'],
      ['What is the main component of natural gas?',
        'Methane|Ethane|Propane|Butane'],
      ['¿Cuál es el componente principal del gas natural?',
        'Metano|Etano|Propano|Butano']],
    [2, 1,
      ['Que aparelho permite observar objetos muito pequenos?',
        'Telescópio|Microscópio|Periscópio|Sextante'],
      ['Which device allows people to observe very small objects?',
        'Telescope|Microscope|Periscope|Sextant'],
      ['¿Qué aparato permite observar objetos muy pequeños?',
        'Telescopio|Microscopio|Periscopio|Sextante']],
    [2, 2,
      ['Qual código identifica de forma única dispositivos em uma rede?',
        'URL|HTML|Endereço IP|HTTP'],
      ['Which code uniquely identifies devices on a network?',
        'URL|HTML|IP address|HTTP'],
      ['¿Qué código identifica de forma única a dispositivos en una red?',
        'URL|HTML|Dirección IP|HTTP']],
    [2, 3,
      ['Em qual estado da matéria as partículas estão ionizadas?',
        'Sólido|Líquido|Gás|Plasma'],
      ['In which state of matter are particles ionized?',
        'Solid|Liquid|Gas|Plasma'],
      ['¿En qué estado de la materia están ionizadas las partículas?',
        'Sólido|Líquido|Gas|Plasma']],
    [2, 0,
      ['Qual cientista descreveu a seleção natural?',
        'Charles Darwin|Antoine Lavoisier|Dmitri Mendeleev|Michael Faraday'],
      ['Which scientist described natural selection?',
        'Charles Darwin|Antoine Lavoisier|Dmitri Mendeleev|Michael Faraday'],
      ['¿Qué científico describió la selección natural?',
        'Charles Darwin|Antoine Lavoisier|Dmitri Mendeleev|Michael Faraday']],
    [3, 1,
      ['Qual planeta tem o período de rotação mais longo do Sistema Solar?',
        'Mercúrio|Vênus|Marte|Netuno'],
      ['Which planet has the longest rotation period in the Solar System?',
        'Mercury|Venus|Mars|Neptune'],
      ['¿Qué planeta tiene el período de rotación más largo del Sistema Solar?',
        'Mercurio|Venus|Marte|Neptuno']],
    [3, 2,
      ['Qual elemento tem o símbolo químico W?',
        'Tântalo|Estanho|Tungstênio|Titânio'],
      ['Which element has the chemical symbol W?',
        'Tantalum|Tin|Tungsten|Titanium'],
      ['¿Qué elemento tiene el símbolo químico W?',
        'Tántalo|Estaño|Wolframio|Titanio']],
    [3, 3,
      ['Qual cientista criou a tabela periódica moderna inicial em 1869?',
        'J. J. Thomson|Ernest Rutherford|Niels Bohr|Dmitri Mendeleev'],
      ['Which scientist created the initial modern periodic table in 1869?',
        'J. J. Thomson|Ernest Rutherford|Niels Bohr|Dmitri Mendeleev'],
      ['¿Qué científico creó la tabla periódica moderna inicial en 1869?',
        'J. J. Thomson|Ernest Rutherford|Niels Bohr|Dmitri Mendeleev']],
    [3, 0,
      ['Qual tipo de onda é usado em aparelhos de ressonância magnética?',
        'Ondas de rádio|Ondas sonoras|Raios X|Ondas oceânicas'],
      ['Which type of wave is used in magnetic resonance imaging?',
        'Radio waves|Sound waves|X-rays|Ocean waves'],
      ['¿Qué tipo de onda se usa en la resonancia magnética?',
        'Ondas de radio|Ondas sonoras|Rayos X|Ondas oceánicas']],
    [3, 1,
      ['Qual estrutura do olho controla a quantidade de luz que entra?',
        'Retina|Íris|Córnea|Nervo óptico'],
      ['Which structure of the eye controls how much light enters?',
        'Retina|Iris|Cornea|Optic nerve'],
      ['¿Qué estructura del ojo controla la cantidad de luz que entra?',
        'Retina|Iris|Córnea|Nervio óptico']],
    [3, 2,
      ['Qual é o nome do limite ao redor de um buraco negro além do qual nada escapa?',
        'Cinturão de asteroides|Nuvem de Oort|Horizonte de eventos|Cinturão de Kuiper'],
      ['What is the boundary around a black hole beyond which nothing escapes called?',
        'Asteroid belt|Oort cloud|Event horizon|Kuiper belt'],
      ['¿Cómo se llama el límite alrededor de un agujero negro más allá del cual nada escapa?',
        'Cinturón de asteroides|Nube de Oort|Horizonte de sucesos|Cinturón de Kuiper']],
    [3, 3,
      ['Que ramo da biologia estuda a classificação dos seres vivos?',
        'Ecologia|Anatomia|Fisiologia|Taxonomia'],
      ['Which branch of biology studies the classification of living things?',
        'Ecology|Anatomy|Physiology|Taxonomy'],
      ['¿Qué rama de la biología estudia la clasificación de los seres vivos?',
        'Ecología|Anatomía|Fisiología|Taxonomía']],
    [3, 0,
      ['Qual unidade mede a frequência de uma onda?',
        'Hertz|Joule|Pascal|Tesla'],
      ['Which unit measures the frequency of a wave?',
        'Hertz|Joule|Pascal|Tesla'],
      ['¿Qué unidad mide la frecuencia de una onda?',
        'Hercio|Julio|Pascal|Tesla']],
    [3, 1,
      ['Qual cientista descobriu os raios X em 1895?',
        'Henri Becquerel|Wilhelm Conrad Röntgen|James Chadwick|Max Born'],
      ['Which scientist discovered X-rays in 1895?',
        'Henri Becquerel|Wilhelm Conrad Röntgen|James Chadwick|Max Born'],
      ['¿Qué científico descubrió los rayos X en 1895?',
        'Henri Becquerel|Wilhelm Conrad Röntgen|James Chadwick|Max Born']],
    [3, 2,
      ['Qual organela celular produz a maior parte do ATP?',
        'Complexo de Golgi|Lisossomo|Mitocôndria|Vacúolo'],
      ['Which cell organelle produces most ATP?',
        'Golgi apparatus|Lysosome|Mitochondrion|Vacuole'],
      ['¿Qué orgánulo celular produce la mayor parte del ATP?',
        'Aparato de Golgi|Lisosoma|Mitocondria|Vacuola']],
    [3, 3,
      ['Qual é o nome do processo em que um sólido passa diretamente a gás?',
        'Condensação|Fusão|Solidificação|Sublimação'],
      ['What is the process in which a solid changes directly into a gas called?',
        'Condensation|Melting|Freezing|Sublimation'],
      ['¿Cómo se llama el proceso en que un sólido pasa directamente a gas?',
        'Condensación|Fusión|Solidificación|Sublimación']],
    [3, 0,
      ['Qual protocolo traduz nomes de domínio em endereços IP?',
        'DNS|FTP|SMTP|SSH'],
      ['Which protocol translates domain names into IP addresses?',
        'DNS|FTP|SMTP|SSH'],
      ['¿Qué protocolo traduce nombres de dominio en direcciones IP?',
        'DNS|FTP|SMTP|SSH']],
    [3, 1,
      ['Qual é a unidade do Sistema Internacional para força?',
        'Joule|Newton|Watt|Volt'],
      ['What is the International System unit of force?',
        'Joule|Newton|Watt|Volt'],
      ['¿Cuál es la unidad del Sistema Internacional para la fuerza?',
        'Julio|Newton|Vatio|Voltio']],
    [3, 2,
      ['Qual gás nobre tem o símbolo químico Ne?',
        'Argônio|Xenônio|Neônio|Criptônio'],
      ['Which noble gas has the chemical symbol Ne?',
        'Argon|Xenon|Neon|Krypton'],
      ['¿Qué gas noble tiene el símbolo químico Ne?',
        'Argón|Xenón|Neón|Criptón']],
    [3, 3,
      ['Qual é a unidade básica da hereditariedade?',
        'Proteína|Cromossomo|Enzima|Gene'],
      ['What is the basic unit of heredity?',
        'Protein|Chromosome|Enzyme|Gene'],
      ['¿Cuál es la unidad básica de la herencia?',
        'Proteína|Cromosoma|Enzima|Gen']],
  ];
  const texto = ([pergunta, alternativas]) => [pergunta, alternativas.split('|')];
  const perguntas = dados.map(([nivel, certa, pt, en, es], indice) => ({
    id: `ciencia-${String(indice + 1).padStart(3, '0')}`,
    nivel,
    certa,
    pt: texto(pt),
    en: texto(en),
    es: texto(es),
  }));
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.ciencia = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
