'use strict';

/* Quiz -- tema "esportes". Cada pergunta: id estavel, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  function q(id, nivel, certa, pt, en, es, op, oe, os) {
    return { id, nivel, certa, pt: [pt, op], en: [en, oe], es: [es, os] };
  }
  const perguntas = [
    q('esportes-001', 1, 0, 'Quantos jogadores de cada time ficam em quadra no basquete?',
      'How many players per team are on the court in basketball?',
      '¿Cuántos jugadores de cada equipo están en la cancha en el baloncesto?',
      ['5', '6', '7', '8'], ['5', '6', '7', '8'], ['5', '6', '7', '8']),
    q('esportes-002', 1, 1, 'Qual esporte é disputado no torneio de Wimbledon?',
      'Which sport is played at the Wimbledon tournament?', '¿Qué deporte se juega en Wimbledon?',
      ['Golfe', 'Tênis', 'Críquete', 'Rúgbi'], ['Golf', 'Tennis', 'Cricket', 'Rugby'],
      ['Golf', 'Tenis', 'Críquet', 'Rugby']),
    q('esportes-003', 1, 2, 'Quantos anéis tem a bandeira olímpica?',
      'How many rings does the Olympic flag have?', '¿Cuántos aros tiene la bandera olímpica?',
      ['3', '4', '5', '6'], ['3', '4', '5', '6'], ['3', '4', '5', '6']),
    q('esportes-004', 1, 3, 'Qual esporte usa uma peteca?', 'Which sport uses a shuttlecock?',
      '¿Qué deporte usa un volante?', ['Tênis', 'Vôlei', 'Squash', 'Badminton'],
      ['Tennis', 'Volleyball', 'Squash', 'Badminton'], ['Tenis', 'Voleibol', 'Squash', 'Bádminton']),
    q('esportes-005', 1, 0, 'Qual astro do basquete ficou conhecido pelo apelido "Air"?',
      'Which basketball star was known by the nickname "Air"?',
      '¿Qué estrella del baloncesto era conocida por el apodo "Air"?',
      ['Michael Jordan', 'Kobe Bryant', 'Larry Bird', 'Magic Johnson'],
      ['Michael Jordan', 'Kobe Bryant', 'Larry Bird', 'Magic Johnson'],
      ['Michael Jordan', 'Kobe Bryant', 'Larry Bird', 'Magic Johnson']),
    q('esportes-006', 1, 1, 'Em qual esporte se usa uma cesta para marcar pontos?',
      'In which sport is a basket used to score points?',
      '¿En qué deporte se usa una canasta para anotar puntos?',
      ['Handebol', 'Basquete', 'Hóquei', 'Rúgbi'], ['Handball', 'Basketball', 'Hockey', 'Rugby'],
      ['Balonmano', 'Baloncesto', 'Hockey', 'Rugby']),
    q('esportes-007', 1, 2, 'Qual modalidade combina natação, ciclismo e corrida?',
      'Which event combines swimming, cycling, and running?',
      '¿Qué disciplina combina natación, ciclismo y carrera?',
      ['Decatlo', 'Heptatlo', 'Triatlo', 'Pentatlo moderno'],
      ['Decathlon', 'Heptathlon', 'Triathlon', 'Modern pentathlon'],
      ['Decatlón', 'Heptatlón', 'Triatlón', 'Pentatlón moderno']),
    q('esportes-008', 1, 3, 'Qual esporte é praticado sobre gelo com patins e um disco?',
      'Which sport is played on ice with skates and a puck?',
      '¿Qué deporte se practica sobre hielo con patines y un disco?',
      ['Curling', 'Patinação artística', 'Bobsleigh', 'Hóquei no gelo'],
      ['Curling', 'Figure skating', 'Bobsleigh', 'Ice hockey'],
      ['Curling', 'Patinaje artístico', 'Bobsleigh', 'Hockey sobre hielo']),
    q('esportes-009', 1, 0, 'Qual cor de medalha é dada ao primeiro colocado olímpico?',
      'What medal color is awarded to first place at the Olympics?',
      '¿Qué color de medalla recibe el primer lugar olímpico?',
      ['Ouro', 'Prata', 'Bronze', 'Cobre'], ['Gold', 'Silver', 'Bronze', 'Copper'],
      ['Oro', 'Plata', 'Bronce', 'Cobre']),
    q('esportes-010', 1, 1, 'Qual esporte é conhecido pela sigla NBA?',
      'Which sport is associated with the acronym NBA?', '¿Con qué deporte se asocia la sigla NBA?',
      ['Beisebol', 'Basquete', 'Hóquei', 'Tênis'], ['Baseball', 'Basketball', 'Hockey', 'Tennis'],
      ['Béisbol', 'Baloncesto', 'Hockey', 'Tenis']),
    q('esportes-011', 1, 2, 'Qual esporte é disputado com arco e flechas?',
      'Which sport is contested with a bow and arrows?', '¿Qué deporte se disputa con arco y flechas?',
      ['Esgrima', 'Tiro esportivo', 'Tiro com arco', 'Dardos'],
      ['Fencing', 'Sport shooting', 'Archery', 'Darts'],
      ['Esgrima', 'Tiro deportivo', 'Tiro con arco', 'Dardos']),
    q('esportes-012', 1, 3, 'Qual objeto é rebatido com um taco no beisebol?',
      'What object is hit with a bat in baseball?', '¿Qué objeto se golpea con un bate en el béisbol?',
      ['Disco', 'Peteca', 'Bola de golfe', 'Bola de beisebol'],
      ['Puck', 'Shuttlecock', 'Golf ball', 'Baseball'],
      ['Disco', 'Volante', 'Pelota de golf', 'Pelota de béisbol']),
    q('esportes-013', 1, 0, 'Qual é a distância de uma corrida de 100 metros?',
      'What is the distance of a 100-meter race?', '¿Cuál es la distancia de una carrera de 100 metros?',
      ['100 metros', '200 metros', '400 metros', '800 metros'],
      ['100 meters', '200 meters', '400 meters', '800 meters'],
      ['100 metros', '200 metros', '400 metros', '800 metros']),
    q('esportes-014', 1, 1, 'Em qual modalidade um atleta salta de uma plataforma para a água?',
      'In which event does an athlete jump from a platform into water?',
      '¿En qué disciplina un atleta salta de una plataforma al agua?',
      ['Natação artística', 'Saltos ornamentais', 'Remo', 'Vela'],
      ['Artistic swimming', 'Diving', 'Rowing', 'Sailing'],
      ['Natación artística', 'Saltos', 'Remo', 'Vela']),
    q('esportes-015', 1, 2, 'Qual esporte usa uma bola oval e um gol em forma de H?',
      'Which sport uses an oval ball and H-shaped goalposts?',
      '¿Qué deporte usa un balón ovalado y postes en forma de H?',
      ['Críquete', 'Beisebol', 'Rúgbi', 'Handebol'],
      ['Cricket', 'Baseball', 'Rugby', 'Handball'],
      ['Críquet', 'Béisbol', 'Rugby', 'Balonmano']),
    q('esportes-016', 1, 3, 'Que instrumento é usado para acertar uma bola no golfe?',
      'What instrument is used to hit a ball in golf?',
      '¿Qué instrumento se usa para golpear una pelota en el golf?',
      ['Raquete', 'Bastão', 'Taco de sinuca', 'Taco de golfe'],
      ['Racket', 'Bat', 'Pool cue', 'Golf club'],
      ['Raqueta', 'Bate', 'Taco de billar', 'Palo de golf']),
    q('esportes-017', 1, 0, 'Qual esporte é praticado em uma piscina com raias?',
      'Which sport is practiced in a pool with lanes?', '¿Qué deporte se practica en una piscina con carriles?',
      ['Natação', 'Remo', 'Surfe', 'Vela'], ['Swimming', 'Rowing', 'Surfing', 'Sailing'],
      ['Natación', 'Remo', 'Surf', 'Vela']),
    q('esportes-018', 1, 1, 'Qual modalidade usa uma barra horizontal e uma vara?',
      'Which event uses a horizontal bar and a pole?', '¿Qué disciplina usa una barra horizontal y una pértiga?',
      ['Salto em distância', 'Salto com vara', 'Salto triplo', 'Arremesso de peso'],
      ['Long jump', 'Pole vault', 'Triple jump', 'Shot put'],
      ['Salto de longitud', 'Salto con pértiga', 'Salto triple', 'Lanzamiento de peso']),
    q('esportes-019', 1, 2, 'Qual esporte tem provas de salto em altura e lançamento de dardo?',
      'Which sport has high jump and javelin throw events?',
      '¿Qué deporte tiene pruebas de salto de altura y lanzamiento de jabalina?',
      ['Natação', 'Ginástica', 'Atletismo', 'Halterofilismo'],
      ['Swimming', 'Gymnastics', 'Athletics', 'Weightlifting'],
      ['Natación', 'Gimnasia', 'Atletismo', 'Halterofilia']),
    q('esportes-020', 1, 3, 'Quantos jogadores de cada equipe ficam em quadra no voleibol?',
      'How many players per team are on the court in volleyball?',
      '¿Cuántos jugadores de cada equipo están en la cancha en el voleibol?',
      ['5', '7', '8', '6'], ['5', '7', '8', '6'], ['5', '7', '8', '6']),
    q('esportes-021', 2, 0, 'Qual é a distância oficial de uma maratona?',
      'What is the official distance of a marathon?', '¿Cuál es la distancia oficial de un maratón?',
      ['42,195 km', '21,097 km', '40 km', '50 km'],
      ['42.195 km', '21.097 km', '40 km', '50 km'],
      ['42,195 km', '21,097 km', '40 km', '50 km']),
    q('esportes-022', 2, 1, 'Em qual esporte aparecem os termos "birdie" e "eagle"?',
      'In which sport do the terms "birdie" and "eagle" appear?',
      '¿En qué deporte aparecen los términos "birdie" y "eagle"?',
      ['Críquete', 'Golfe', 'Boliche', 'Beisebol'], ['Cricket', 'Golf', 'Bowling', 'Baseball'],
      ['Críquet', 'Golf', 'Bolos', 'Béisbol']),
    q('esportes-023', 2, 2, 'Qual país sediou os Jogos Olímpicos de 2008?',
      'Which country hosted the 2008 Olympic Games?', '¿Qué país fue sede de los Juegos Olímpicos de 2008?',
      ['Grécia', 'Japão', 'China', 'Reino Unido'], ['Greece', 'Japan', 'China', 'United Kingdom'],
      ['Grecia', 'Japón', 'China', 'Reino Unido']),
    q('esportes-024', 2, 3, 'Qual equipe de Fórmula 1 tem um cavalo empinado como símbolo?',
      'Which Formula 1 team has a prancing horse as its symbol?',
      '¿Qué equipo de Fórmula 1 tiene un caballo rampante como símbolo?',
      ['McLaren', 'Williams', 'Lotus', 'Ferrari'], ['McLaren', 'Williams', 'Lotus', 'Ferrari'],
      ['McLaren', 'Williams', 'Lotus', 'Ferrari']),
    q('esportes-025', 2, 0, 'Em qual cidade foram realizados os primeiros Jogos Olímpicos modernos, em 1896?',
      'In which city were the first modern Olympic Games held, in 1896?',
      '¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos, en 1896?',
      ['Atenas', 'Paris', 'Londres', 'Roma'], ['Athens', 'Paris', 'London', 'Rome'],
      ['Atenas', 'París', 'Londres', 'Roma']),
    q('esportes-026', 2, 1, 'Quantos pontos vale um lance livre no basquete?',
      'How many points is a free throw worth in basketball?',
      '¿Cuántos puntos vale un tiro libre en el baloncesto?',
      ['2', '1', '3', '4'], ['2', '1', '3', '4'], ['2', '1', '3', '4']),
    q('esportes-027', 2, 2, 'Qual superfície é tradicionalmente usada em Wimbledon?',
      'Which surface is traditionally used at Wimbledon?', '¿Qué superficie se usa tradicionalmente en Wimbledon?',
      ['Saibro', 'Piso duro', 'Grama', 'Carpete'],
      ['Clay', 'Hard court', 'Grass', 'Carpet'], ['Tierra batida', 'Pista dura', 'Hierba', 'Moqueta']),
    q('esportes-028', 2, 3, 'Qual estilo de natação é nadado de barriga para cima?',
      'Which swimming stroke is swum on the back, face up?',
      '¿Qué estilo de natación se nada boca arriba?',
      ['Peito', 'Livre', 'Borboleta', 'Costas'],
      ['Breaststroke', 'Freestyle', 'Butterfly', 'Backstroke'],
      ['Braza', 'Libre', 'Mariposa', 'Espalda']),
    q('esportes-029', 2, 0, 'Qual é o comprimento de uma piscina olímpica?',
      'What is the length of an Olympic swimming pool?', '¿Cuál es la longitud de una piscina olímpica?',
      ['50 metros', '25 metros', '75 metros', '100 metros'],
      ['50 meters', '25 meters', '75 meters', '100 meters'],
      ['50 metros', '25 metros', '75 metros', '100 metros']),
    q('esportes-030', 2, 1, 'Qual atleta venceu oito medalhas de ouro na natação em Pequim, em 2008?',
      'Which athlete won eight swimming gold medals in Beijing in 2008?',
      '¿Qué atleta ganó ocho medallas de oro en natación en Pekín en 2008?',
      ['Mark Spitz', 'Michael Phelps', 'Ian Thorpe', 'Ryan Lochte'],
      ['Mark Spitz', 'Michael Phelps', 'Ian Thorpe', 'Ryan Lochte'],
      ['Mark Spitz', 'Michael Phelps', 'Ian Thorpe', 'Ryan Lochte']),
    q('esportes-031', 2, 2, 'Em qual esporte é usado um sabre?', 'In which sport is a saber used?',
      '¿En qué deporte se usa un sable?', ['Boxe', 'Taekwondo', 'Esgrima', 'Judô'],
      ['Boxing', 'Taekwondo', 'Fencing', 'Judo'], ['Boxeo', 'Taekwondo', 'Esgrima', 'Judo']),
    q('esportes-032', 2, 3, 'Quantas voltas há em 1.500 metros numa pista olímpica de atletismo?',
      'How many laps are in 1,500 meters on an Olympic athletics track?',
      '¿Cuántas vueltas hay en 1.500 metros en una pista olímpica de atletismo?',
      ['2', '3', '3,5', '3,75'], ['2', '3', '3.5', '3.75'], ['2', '3', '3,5', '3,75']),
    q('esportes-033', 2, 0, 'Qual modalidade de ciclismo é disputada numa pista inclinada fechada?',
      'Which cycling discipline is contested on an enclosed banked track?',
      '¿Qué modalidad de ciclismo se disputa en una pista cerrada e inclinada?',
      ['Ciclismo de pista', 'Ciclismo de estrada', 'BMX', 'Mountain bike'],
      ['Track cycling', 'Road cycling', 'BMX', 'Mountain biking'],
      ['Ciclismo en pista', 'Ciclismo de ruta', 'BMX', 'Ciclismo de montaña']),
    q('esportes-034', 2, 1, 'Qual seleção venceu a primeira Copa do Mundo de Críquete, em 1975?',
      'Which team won the first Cricket World Cup, in 1975?',
      '¿Qué selección ganó la primera Copa del Mundo de Críquet, en 1975?',
      ['Austrália', 'Índias Ocidentais', 'Inglaterra', 'Índia'],
      ['Australia', 'West Indies', 'England', 'India'],
      ['Australia', 'West Indies', 'England', 'India']),
    q('esportes-035', 2, 2, 'Qual país é associado à origem do judô?',
      'Which country is associated with the origin of judo?', '¿Con qué país se asocia el origen del judo?',
      ['China', 'Coreia do Sul', 'Japão', 'Tailândia'],
      ['China', 'South Korea', 'Japan', 'Thailand'], ['China', 'Corea del Sur', 'Japón', 'Tailandia']),
    q('esportes-036', 2, 3, 'Qual Grand Slam de tênis é jogado em quadras de saibro?',
      'Which tennis Grand Slam is played on clay courts?',
      '¿Qué Grand Slam de tenis se juega en canchas de tierra batida?',
      ['Australian Open', 'Wimbledon', 'US Open', 'Roland-Garros'],
      ['Australian Open', 'Wimbledon', 'US Open', 'Roland-Garros'],
      ['Australian Open', 'Wimbledon', 'US Open', 'Roland-Garros']),
    q('esportes-037', 2, 0, 'Em qual esporte se marca um "home run"?',
      'In which sport is a "home run" scored?', '¿En qué deporte se anota un "home run"?',
      ['Beisebol', 'Críquete', 'Golfe', 'Rúgbi'], ['Baseball', 'Cricket', 'Golf', 'Rugby'],
      ['Béisbol', 'Críquet', 'Golf', 'Rugby']),
    q('esportes-038', 2, 1, 'Qual país sediou os primeiros Jogos Olímpicos de Inverno, em 1924?',
      'Which country hosted the first Winter Olympic Games, in 1924?',
      '¿Qué país fue sede de los primeros Juegos Olímpicos de Invierno, en 1924?',
      ['Suíça', 'França', 'Noruega', 'Canadá'], ['Switzerland', 'France', 'Norway', 'Canada'],
      ['Suiza', 'Francia', 'Noruega', 'Canadá']),
    q('esportes-039', 2, 2, 'Qual prova do atletismo consiste em lançar uma esfera metálica?',
      'Which athletics event consists of throwing a metal sphere?',
      '¿Qué prueba de atletismo consiste en lanzar una esfera metálica?',
      ['Lançamento de disco', 'Lançamento de dardo', 'Arremesso de peso', 'Lançamento de martelo'],
      ['Discus throw', 'Javelin throw', 'Shot put', 'Hammer throw'],
      ['Lanzamiento de disco', 'Lanzamiento de jabalina', 'Lanzamiento de peso', 'Lanzamiento de martillo']),
    q('esportes-040', 2, 3, 'Qual piloto venceu o Campeonato Mundial de Fórmula 1 de 1991?',
      'Which driver won the 1991 Formula 1 World Championship?',
      '¿Qué piloto ganó el Campeonato Mundial de Fórmula 1 de 1991?',
      ['Alain Prost', 'Nigel Mansell', 'Michael Schumacher', 'Ayrton Senna'],
      ['Alain Prost', 'Nigel Mansell', 'Michael Schumacher', 'Ayrton Senna'],
      ['Alain Prost', 'Nigel Mansell', 'Michael Schumacher', 'Ayrton Senna']),
    q('esportes-041', 2, 0, 'Qual seleção venceu o torneio masculino de basquete nos Jogos Olímpicos de 1992?',
      "Which team won the men's basketball tournament at the 1992 Olympic Games?",
      '¿Qué selección ganó el torneo masculino de baloncesto en los Juegos Olímpicos de 1992?',
      ['Estados Unidos', 'Croácia', 'Lituânia', 'Espanha'],
      ['United States', 'Croatia', 'Lithuania', 'Spain'],
      ['Estados Unidos', 'Croacia', 'Lituania', 'España']),
    q('esportes-042', 2, 1, 'Como se chama a modalidade equestre com obstáculos para cavalo e cavaleiro?',
      'What is the equestrian event with obstacles for horse and rider called?',
      '¿Cómo se llama la disciplina ecuestre con obstáculos para caballo y jinete?',
      ['Adestramento', 'Saltos', 'Polo', 'Enduro equestre'],
      ['Dressage', 'Jumping', 'Polo', 'Endurance riding'],
      ['Doma', 'Salto', 'Polo', 'Resistencia ecuestre']),
    q('esportes-043', 2, 2, 'No tênis, como se chama uma pontuação de zero?',
      'In tennis, what is a score of zero called?', 'En tenis, ¿cómo se llama una puntuación de cero?',
      ['Deuce', 'Advantage', 'Love', 'Break point'],
      ['Deuce', 'Advantage', 'Love', 'Break point'], ['Deuce', 'Advantage', 'Love', 'Break point']),
    q('esportes-044', 2, 3, 'Qual país venceu a Copa do Mundo de Rúgbi de 1995?',
      'Which country won the 1995 Rugby World Cup?', '¿Qué país ganó la Copa del Mundo de Rugby de 1995?',
      ['Nova Zelândia', 'Austrália', 'Inglaterra', 'África do Sul'],
      ['New Zealand', 'Australia', 'England', 'South Africa'],
      ['Nueva Zelanda', 'Australia', 'Inglaterra', 'Sudáfrica']),
    q('esportes-045', 2, 0, 'Qual ginasta obteve o primeiro 10 perfeito olímpico em 1976?',
      'Which gymnast earned the first perfect Olympic 10 in 1976?',
      '¿Qué gimnasta obtuvo el primer 10 perfecto olímpico en 1976?',
      ['Nadia Comăneci', 'Olga Korbut', 'Nellie Kim', 'Simone Biles'],
      ['Nadia Comăneci', 'Olga Korbut', 'Nellie Kim', 'Simone Biles'],
      ['Nadia Comăneci', 'Olga Korbut', 'Nellie Kim', 'Simone Biles']),
    q('esportes-046', 3, 1, 'Qual atleta venceu o decatlo nos Jogos Olímpicos de 1976?',
      'Which athlete won the decathlon at the 1976 Olympic Games?',
      '¿Qué atleta ganó el decatlón en los Juegos Olímpicos de 1976?',
      ['Daley Thompson', 'Bruce Jenner', 'Ashton Eaton', 'Roman Šebrle'],
      ['Daley Thompson', 'Bruce Jenner', 'Ashton Eaton', 'Roman Šebrle'],
      ['Daley Thompson', 'Bruce Jenner', 'Ashton Eaton', 'Roman Šebrle']),
    q('esportes-047', 3, 2, 'Qual seleção ganhou o ouro feminino de hóquei no gelo nos Jogos de 1998?',
      "Which team won women's ice hockey gold at the 1998 Olympic Games?",
      '¿Qué selección ganó el oro femenino de hockey sobre hielo en los Juegos de 1998?',
      ['Canadá', 'Finlândia', 'Estados Unidos', 'Rússia'],
      ['Canada', 'Finland', 'United States', 'Russia'],
      ['Canadá', 'Finlandia', 'Estados Unidos', 'Rusia']),
    q('esportes-048', 3, 3, 'Quem venceu o torneio masculino de simples de Wimbledon em 1980?',
      "Who won the men's singles tournament at Wimbledon in 1980?",
      '¿Quién ganó el torneo individual masculino de Wimbledon en 1980?',
      ['John McEnroe', 'Jimmy Connors', 'Ivan Lendl', 'Björn Borg'],
      ['John McEnroe', 'Jimmy Connors', 'Ivan Lendl', 'Björn Borg'],
      ['John McEnroe', 'Jimmy Connors', 'Ivan Lendl', 'Björn Borg']),
    q('esportes-049', 3, 0, 'Qual piloto venceu o Grande Prêmio de Mônaco de Fórmula 1 de 1992?',
      'Which driver won the 1992 Formula 1 Monaco Grand Prix?',
      '¿Qué piloto ganó el Gran Premio de Mónaco de Fórmula 1 de 1992?',
      ['Ayrton Senna', 'Nigel Mansell', 'Riccardo Patrese', 'Michael Schumacher'],
      ['Ayrton Senna', 'Nigel Mansell', 'Riccardo Patrese', 'Michael Schumacher'],
      ['Ayrton Senna', 'Nigel Mansell', 'Riccardo Patrese', 'Michael Schumacher']),
    q('esportes-050', 3, 1, 'Qual país venceu a primeira Copa do Mundo de Rúgbi, em 1987?',
      'Which country won the first Rugby World Cup, in 1987?',
      '¿Qué país ganó la primera Copa del Mundo de Rugby, en 1987?',
      ['Austrália', 'Nova Zelândia', 'França', 'África do Sul'],
      ['Australia', 'New Zealand', 'France', 'South Africa'],
      ['Australia', 'Nueva Zelanda', 'Francia', 'Sudáfrica']),
    q('esportes-051', 3, 2, 'Qual piloto venceu o Campeonato Mundial de Fórmula 1 de 1976?',
      'Which driver won the 1976 Formula 1 World Championship?',
      '¿Qué piloto ganó el Campeonato Mundial de Fórmula 1 de 1976?',
      ['Niki Lauda', 'Mario Andretti', 'James Hunt', 'Jody Scheckter'],
      ['Niki Lauda', 'Mario Andretti', 'James Hunt', 'Jody Scheckter'],
      ['Niki Lauda', 'Mario Andretti', 'James Hunt', 'Jody Scheckter']),
    q('esportes-052', 3, 3, 'Qual seleção venceu o hóquei no gelo masculino nos Jogos Olímpicos de 2002?',
      "Which team won the men's ice hockey tournament at the 2002 Olympic Games?",
      '¿Qué selección ganó el torneo masculino de hockey sobre hielo en los Juegos Olímpicos de 2002?',
      ['Estados Unidos', 'Rússia', 'Suécia', 'Canadá'], ['United States', 'Russia', 'Sweden', 'Canada'],
      ['Estados Unidos', 'Rusia', 'Suecia', 'Canadá']),
    q('esportes-053', 3, 0, 'Qual atleta venceu a maratona feminina nos Jogos Olímpicos de 1984?',
      "Which athlete won the women's marathon at the 1984 Olympic Games?",
      '¿Qué atleta ganó el maratón femenino en los Juegos Olímpicos de 1984?',
      ['Joan Benoit', 'Grete Waitz', 'Rosa Mota', 'Tegla Loroupe'],
      ['Joan Benoit', 'Grete Waitz', 'Rosa Mota', 'Tegla Loroupe'],
      ['Joan Benoit', 'Grete Waitz', 'Rosa Mota', 'Tegla Loroupe']),
    q('esportes-054', 3, 1, 'Qual seleção venceu o torneio masculino de handebol nos Jogos Olímpicos de 2016?',
      "Which team won the men's handball tournament at the 2016 Olympic Games?",
      '¿Qué selección ganó el torneo masculino de balonmano en los Juegos Olímpicos de 2016?',
      ['França', 'Dinamarca', 'Alemanha', 'Croácia'], ['France', 'Denmark', 'Germany', 'Croatia'],
      ['Francia', 'Dinamarca', 'Alemania', 'Croacia']),
    q('esportes-055', 3, 2, 'Quem venceu o torneio feminino de simples do US Open de 1999?',
      "Who won the women's singles tournament at the 1999 US Open?",
      '¿Quién ganó el torneo individual femenino del US Open de 1999?',
      ['Venus Williams', 'Lindsay Davenport', 'Serena Williams', 'Martina Hingis'],
      ['Venus Williams', 'Lindsay Davenport', 'Serena Williams', 'Martina Hingis'],
      ['Venus Williams', 'Lindsay Davenport', 'Serena Williams', 'Martina Hingis']),
    q('esportes-056', 3, 3, 'Quantas medalhas de ouro olímpicas Michael Phelps tinha ao fim dos Jogos de 2016?',
      'How many Olympic gold medals did Michael Phelps have at the end of the 2016 Games?',
      '¿Cuántas medallas de oro olímpicas tenía Michael Phelps al final de los Juegos de 2016?',
      ['18', '20', '21', '23'], ['18', '20', '21', '23'], ['18', '20', '21', '23']),
    q('esportes-057', 3, 0, 'Qual país venceu a Copa do Mundo de Críquete de 1983?',
      'Which country won the 1983 Cricket World Cup?', '¿Qué país ganó la Copa del Mundo de Críquet de 1983?',
      ['Índia', 'Austrália', 'Índias Ocidentais', 'Inglaterra'],
      ['India', 'Australia', 'West Indies', 'England'],
      ['India', 'Australia', 'Indias Occidentales', 'Inglaterra']),
    q('esportes-058', 3, 1, 'Qual atleta venceu a prova masculina de 100 metros nos Jogos Olímpicos de 1984?',
      "Which athlete won the men's 100-meter race at the 1984 Olympic Games?",
      '¿Qué atleta ganó la carrera masculina de 100 metros en los Juegos Olímpicos de 1984?',
      ['Ben Johnson', 'Carl Lewis', 'Linford Christie', 'Donovan Bailey'],
      ['Ben Johnson', 'Carl Lewis', 'Linford Christie', 'Donovan Bailey'],
      ['Ben Johnson', 'Carl Lewis', 'Linford Christie', 'Donovan Bailey']),
    q('esportes-059', 3, 2, 'Qual país venceu o ouro do revezamento feminino 4 × 100 metros nos Jogos de 2012?',
      "Which country won women's 4 × 100-meter relay gold at the 2012 Olympic Games?",
      '¿Qué país ganó el oro femenino del relevo 4 × 100 metros en los Juegos de 2012?',
      ['Jamaica', 'França', 'Estados Unidos', 'Nigéria'],
      ['Jamaica', 'France', 'United States', 'Nigeria'],
      ['Jamaica', 'Francia', 'Estados Unidos', 'Nigeria']),
    q('esportes-060', 3, 3, 'Quem tinha mais títulos de Grand Slam no tênis masculino ao fim de 2022?',
      "Who had the most men's tennis Grand Slam titles at the end of 2022?",
      '¿Quién tenía más títulos de Grand Slam en el tenis masculino a finales de 2022?',
      ['Roger Federer', 'Novak Djokovic', 'Pete Sampras', 'Rafael Nadal'],
      ['Roger Federer', 'Novak Djokovic', 'Pete Sampras', 'Rafael Nadal'],
      ['Roger Federer', 'Novak Djokovic', 'Pete Sampras', 'Rafael Nadal']),
  ];
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.esportes = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
