'use strict';

/* Banco local do Quiz: id estavel, tema, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  const q = (id, nivel, certa, pt, en, es) => ({ id: `filmes-${id}`, nivel, certa, pt, en, es });
  const diretor = (id, nivel, certa, titulos, alternativas) => q(id, nivel, certa,
    [`Quem dirigiu "${titulos[0]}"?`, alternativas],
    [`Who directed "${titulos[1]}"?`, alternativas],
    [`¿Quién dirigió "${titulos[2]}"?`, alternativas]);
  const oscar = (id, nivel, certa, ano, pt, en, es) => q(id, nivel, certa,
    [`Qual filme venceu o Oscar de Melhor Filme na cerimônia de ${ano}?`, pt],
    [`Which film won the Oscar for Best Picture at the ${ano} ceremony?`, en],
    [`¿Qué película ganó el Óscar a la mejor película en la ceremonia de ${ano}?`, es]);
  const perguntas = [
    q('001', 1, 1,
      ['Qual estúdio produziu "Toy Story"?',
      ['DreamWorks',
      'Pixar',
      'Illumination',
      'Blue Sky']],
      ['Which studio produced "Toy Story"?',
      ['DreamWorks',
      'Pixar',
      'Illumination',
      'Blue Sky']],
      ['¿Qué estudio produjo "Toy Story"?',
      ['DreamWorks',
      'Pixar',
      'Illumination',
      'Blue Sky']]),
    diretor('002', 2, 2,
      ['Titanic',
      'Titanic',
      'Titanic'],
      ['Steven Spielberg',
      'Ridley Scott',
      'James Cameron',
      'Christopher Nolan']),
    q('003', 1, 0,
      ['Qual bruxinho criado por J. K. Rowling estuda em Hogwarts?',
      ['Harry Potter',
      'Percy Jackson',
      'Merlin',
      'Gandalf']],
      ['Which young wizard created by J. K. Rowling studies at Hogwarts?',
      ['Harry Potter',
      'Percy Jackson',
      'Merlin',
      'Gandalf']],
      ['¿Qué joven mago creado por J. K. Rowling estudia en Hogwarts?',
      ['Harry Potter',
      'Percy Jackson',
      'Merlin',
      'Gandalf']]),
    q('004', 2, 3,
      ['Qual série é baseada nos livros "As Crônicas de Gelo e Fogo", de George R. R. Martin?',
      ['Vikings',
      'The Witcher',
      'Outlander',
      'Game of Thrones']],
      ['Which series is based on the books "A Song of Ice and Fire", by George R. R. Martin?',
      ['Vikings',
      'The Witcher',
      'Outlander',
      'Game of Thrones']],
      ['¿Qué serie está basada en los libros "Canción de hielo y fuego", de George R. R. Martin?',
      ['Vikings',
      'The Witcher',
      'Outlander',
      'Juego de tronos']]),
    q('005', 1, 2,
      ['Qual personagem de Star Wars é o pai de Luke Skywalker?',
      ['Obi-Wan Kenobi',
      'Han Solo',
      'Darth Vader',
      'Yoda']],
      ['Which Star Wars character is the father of Luke Skywalker?',
      ['Obi-Wan Kenobi',
      'Han Solo',
      'Darth Vader',
      'Yoda']],
      ['¿Qué personaje de Star Wars es el padre de Luke Skywalker?',
      ['Obi-Wan Kenobi',
      'Han Solo',
      'Darth Vader',
      'Yoda']]),
    oscar('006', 2, 0, 2020,
      ['Parasita',
      'Jojo Rabbit',
      '1917',
      'Coringa'],
      ['Parasite',
      'Jojo Rabbit',
      '1917',
      'Joker'],
      ['Parásitos',
      'Jojo Rabbit',
      '1917',
      'Joker']),
    diretor('007', 2, 1,
      ['O Poderoso Chefão',
      'The Godfather',
      'El padrino'],
      ['Martin Scorsese',
      'Francis Ford Coppola',
      'Brian De Palma',
      'Sidney Lumet']),
    q('008', 1, 3,
      ['Qual ator interpreta Jack Sparrow em "Piratas do Caribe"?',
      ['Orlando Bloom',
      'Geoffrey Rush',
      'Brad Pitt',
      'Johnny Depp']],
      ['Which actor plays Jack Sparrow in "Pirates of the Caribbean"?',
      ['Orlando Bloom',
      'Geoffrey Rush',
      'Brad Pitt',
      'Johnny Depp']],
      ['¿Qué actor interpreta a Jack Sparrow en "Piratas del Caribe"?',
      ['Orlando Bloom',
      'Geoffrey Rush',
      'Brad Pitt',
      'Johnny Depp']]),
    q('009', 2, 0,
      ['Quem dirigiu a trilogia "O Senhor dos Anéis" no cinema?',
      ['Peter Jackson',
      'Tim Burton',
      'Sam Raimi',
      'George Lucas']],
      ['Who directed "The Lord of the Rings" film trilogy?',
      ['Peter Jackson',
      'Tim Burton',
      'Sam Raimi',
      'George Lucas']],
      ['¿Quién dirigió la trilogía cinematográfica de "El señor de los anillos"?',
      ['Peter Jackson',
      'Tim Burton',
      'Sam Raimi',
      'George Lucas']]),
    diretor('010', 3, 2,
      ['Os Sete Samurais',
      'Seven Samurai',
      'Los siete samuráis'],
      ['Hayao Miyazaki',
      'Yasujirō Ozu',
      'Akira Kurosawa',
      'Takeshi Kitano']),
    q('011', 1, 1,
      ['Qual personagem é o jovem leão protagonista de "O Rei Leão"?',
      ['Mufasa',
      'Simba',
      'Scar',
      'Timon']],
      ['Which character is the young lion protagonist of "The Lion King"?',
      ['Mufasa',
      'Simba',
      'Scar',
      'Timon']],
      ['¿Qué personaje es el joven león protagonista de "El rey león"?',
      ['Mufasa',
      'Simba',
      'Scar',
      'Timon']]),
    q('012', 1, 2,
      ['Qual irmã possui poderes de gelo em "Frozen"?',
      ['Anna',
      'Olaf',
      'Elsa',
      'Kristoff']],
      ['Which sister has ice powers in "Frozen"?',
      ['Anna',
      'Olaf',
      'Elsa',
      'Kristoff']],
      ['¿Qué hermana tiene poderes de hielo en "Frozen"?',
      ['Anna',
      'Olaf',
      'Elsa',
      'Kristoff']]),
    q('013', 2, 0,
      ['Quem dirigiu "Matrix"?',
      ['Lana e Lilly Wachowski',
      'Joel e Ethan Coen',
      'Anthony e Joe Russo',
      'Danny e Michael Philippou']],
      ['Who directed "The Matrix"?',
      ['Lana and Lilly Wachowski',
      'Joel and Ethan Coen',
      'Anthony and Joe Russo',
      'Danny and Michael Philippou']],
      ['¿Quién dirigió "Matrix"?',
      ['Lana y Lilly Wachowski',
      'Joel y Ethan Coen',
      'Anthony y Joe Russo',
      'Danny y Michael Philippou']]),
    q('014', 1, 3,
      ['Qual carro é a máquina do tempo em "De Volta para o Futuro"?',
      ['Ford Mustang',
      'Volkswagen Fusca',
      'Chevrolet Bel Air',
      'DeLorean DMC-12']],
      ['Which car is the time machine in "Back to the Future"?',
      ['Ford Mustang',
      'Volkswagen Beetle',
      'Chevrolet Bel Air',
      'DeLorean DMC-12']],
      ['¿Qué automóvil es la máquina del tiempo en "Volver al futuro"?',
      ['Ford Mustang',
      'Volkswagen Beetle',
      'Chevrolet Bel Air',
      'DeLorean DMC-12']]),
    oscar('015', 2, 1, 1995,
      ['Pulp Fiction',
      'Forrest Gump',
      'Um Sonho de Liberdade',
      'Quatro Casamentos e um Funeral'],
      ['Pulp Fiction',
      'Forrest Gump',
      'The Shawshank Redemption',
      'Four Weddings and a Funeral'],
      ['Pulp Fiction',
      'Forrest Gump',
      'Cadena perpetua',
      'Cuatro bodas y un funeral']),
    diretor('016', 1, 2,
      ['Tubarão',
      'Jaws',
      'Tiburón'],
      ['George Lucas',
      'Robert Zemeckis',
      'Steven Spielberg',
      'James Cameron']),
    q('017', 2, 0,
      ['Quem escreveu o romance que originou o filme "Jurassic Park"?',
      ['Michael Crichton',
      'Stephen King',
      'Philip K. Dick',
      'H. G. Wells']],
      ['Who wrote the novel that became the film "Jurassic Park"?',
      ['Michael Crichton',
      'Stephen King',
      'Philip K. Dick',
      'H. G. Wells']],
      ['¿Quién escribió la novela que originó la película "Parque Jurásico"?',
      ['Michael Crichton',
      'Stephen King',
      'Philip K. Dick',
      'H. G. Wells']]),
    q('018', 1, 3,
      ['Que tipo de peixe é Nemo em "Procurando Nemo"?',
      ['Peixe-dourado',
      'Cavalo-marinho',
      'Peixe-espada',
      'Peixe-palhaço']],
      ['What kind of fish is Nemo in "Finding Nemo"?',
      ['Goldfish',
      'Seahorse',
      'Swordfish',
      'Clownfish']],
      ['¿Qué tipo de pez es Nemo en "Buscando a Nemo"?',
      ['Pez dorado',
      'Caballito de mar',
      'Pez espada',
      'Pez payaso']]),
    q('019', 2, 1,
      ['Qual estúdio japonês produziu "A Viagem de Chihiro"?',
      ['Toei Animation',
      'Studio Ghibli',
      'Madhouse',
      'Kyoto Animation']],
      ['Which Japanese studio produced "Spirited Away"?',
      ['Toei Animation',
      'Studio Ghibli',
      'Madhouse',
      'Kyoto Animation']],
      ['¿Qué estudio japonés produjo "El viaje de Chihiro"?',
      ['Toei Animation',
      'Studio Ghibli',
      'Madhouse',
      'Kyoto Animation']]),
    diretor('020', 3, 2,
      ['Psicose',
      'Psycho',
      'Psicosis'],
      ['Billy Wilder',
      'Orson Welles',
      'Alfred Hitchcock',
      'John Ford']),
    q('021', 1, 0,
      ['A qual casa de Hogwarts Harry Potter pertence?',
      ['Grifinória',
      'Sonserina',
      'Corvinal',
      'Lufa-Lufa']],
      ['Which Hogwarts house does Harry Potter belong to?',
      ['Gryffindor',
      'Slytherin',
      'Ravenclaw',
      'Hufflepuff']],
      ['¿A qué casa de Hogwarts pertenece Harry Potter?',
      ['Gryffindor',
      'Slytherin',
      'Ravenclaw',
      'Hufflepuff']]),
    q('022', 2, 3,
      ['Qual ator dá voz a Shrek no original em inglês?',
      ['Eddie Murphy',
      'Cameron Diaz',
      'Antonio Banderas',
      'Mike Myers']],
      ['Which actor voices Shrek in the original English version?',
      ['Eddie Murphy',
      'Cameron Diaz',
      'Antonio Banderas',
      'Mike Myers']],
      ['¿Qué actor da voz a Shrek en la versión original en inglés?',
      ['Eddie Murphy',
      'Cameron Diaz',
      'Antonio Banderas',
      'Mike Myers']]),
    oscar('023', 2, 1, 2001,
      ['Erin Brockovich',
      'Gladiador',
      'O Tigre e o Dragão',
      'Chocolat'],
      ['Erin Brockovich',
      'Gladiator',
      'Crouching Tiger, Hidden Dragon',
      'Chocolat'],
      ['Erin Brockovich',
      'Gladiator',
      'Tigre y dragón',
      'Chocolat']),
    diretor('024', 3, 2,
      ['Alien',
      'Alien',
      'Alien'],
      ['David Cronenberg',
      'John Carpenter',
      'Ridley Scott',
      'Paul Verhoeven']),
    diretor('025', 3, 0,
      ['O Labirinto do Fauno', "Pan's Labyrinth",
      'El laberinto del fauno'],
      ['Guillermo del Toro',
      'Alejandro G. Iñárritu',
      'Alfonso Cuarón',
      'Pedro Almodóvar']),
    oscar('026', 2, 1, 2000,
      ['O Sexto Sentido',
      'Beleza Americana',
      'À Espera de um Milagre',
      'O Informante'],
      ['The Sixth Sense',
      'American Beauty',
      'The Green Mile',
      'The Insider'],
      ['El sexto sentido',
      'American Beauty',
      'La milla verde',
      'El dilema']),
    q('027', 2, 3,
      ['Qual personagem é o rato cozinheiro de "Ratatouille"?',
      ['Linguini',
      'Anton Ego',
      'Skinner',
      'Remy']],
      ['Which character is the rat chef in "Ratatouille"?',
      ['Linguini',
      'Anton Ego',
      'Skinner',
      'Remy']],
      ['¿Qué personaje es la rata cocinera de "Ratatouille"?',
      ['Linguini',
      'Anton Ego',
      'Skinner',
      'Remy']]),
    diretor('028', 1, 0,
      ['A Origem',
      'Inception',
      'El origen'],
      ['Christopher Nolan',
      'David Fincher',
      'Darren Aronofsky',
      'Denis Villeneuve']),
    oscar('029', 3, 2, 2011,
      ['A Rede Social',
      'A Origem',
      'O Discurso do Rei',
      'Cisne Negro'],
      ['The Social Network',
      'Inception', "The King's Speech",
      'Black Swan'],
      ['La red social',
      'El origen',
      'El discurso del rey',
      'Cisne negro']),
    diretor('030', 2, 1,
      ['A Viagem de Chihiro',
      'Spirited Away',
      'El viaje de Chihiro'],
      ['Isao Takahata',
      'Hayao Miyazaki',
      'Satoshi Kon',
      'Mamoru Hosoda']),
    q('031', 3, 3,
      ['Qual ator interpreta Rick Blaine em "Casablanca"?',
      ['Cary Grant',
      'James Stewart',
      'Clark Gable',
      'Humphrey Bogart']],
      ['Which actor plays Rick Blaine in "Casablanca"?',
      ['Cary Grant',
      'James Stewart',
      'Clark Gable',
      'Humphrey Bogart']],
      ['¿Qué actor interpreta a Rick Blaine en "Casablanca"?',
      ['Cary Grant',
      'James Stewart',
      'Clark Gable',
      'Humphrey Bogart']]),
    diretor('032', 2, 0,
      ['Mad Max: Estrada da Fúria',
      'Mad Max: Fury Road',
      'Mad Max: Furia en el camino'],
      ['George Miller',
      'Peter Jackson',
      'Zack Snyder',
      'James Mangold']),
    q('033', 1, 1,
      ['Como se chama a lua habitada em "Avatar"?',
      ['Endor',
      'Pandora',
      'Arrakis',
      'Krypton']],
      ['What is the inhabited moon called in "Avatar"?',
      ['Endor',
      'Pandora',
      'Arrakis',
      'Krypton']],
      ['¿Cómo se llama la luna habitada en "Avatar"?',
      ['Endor',
      'Pandora',
      'Arrakis',
      'Krypton']]),
    q('034', 1, 2,
      ['Qual país fictício é o lar do Pantera Negra?',
      ['Genosha',
      'Latveria',
      'Wakanda',
      'Themyscira']],
      ['Which fictional country is the home of Black Panther?',
      ['Genosha',
      'Latveria',
      'Wakanda',
      'Themyscira']],
      ['¿Qué país ficticio es el hogar de Pantera Negra?',
      ['Genosha',
      'Latveria',
      'Wakanda',
      'Themyscira']]),
    q('035', 3, 3,
      ['Em que ano estreou "Branca de Neve e os Sete Anões", o primeiro longa de animação da Disney?',
      ['1921',
      '1929',
      '1933',
      '1937']],
      ['In which year was "Snow White and the Seven Dwarfs", the first Disney animated feature, released?',
      ['1921',
      '1929',
      '1933',
      '1937']],
      ['¿En qué año se estrenó "Blancanieves y los siete enanitos", el primer largometraje animado de Disney?',
      ['1921',
      '1929',
      '1933',
      '1937']]),
    diretor('036', 3, 0,
      ['O Silêncio dos Inocentes',
      'The Silence of the Lambs',
      'El silencio de los corderos'],
      ['Jonathan Demme',
      'David Lynch',
      'Alan Parker',
      'Adrian Lyne']),
    q('037', 1, 1,
      ['Qual é o nome do menino protagonista de "Viva: A Vida é uma Festa"?',
      ['Héctor',
      'Miguel',
      'Ernesto',
      'Dante']],
      ['What is the name of the boy protagonist in "Coco"?',
      ['Héctor',
      'Miguel',
      'Ernesto',
      'Dante']],
      ['¿Cómo se llama el niño protagonista de "Coco"?',
      ['Héctor',
      'Miguel',
      'Ernesto',
      'Dante']]),
    q('038', 1, 2,
      ['Qual ator interpreta o personagem-título em "O Exterminador do Futuro"?',
      ['Sylvester Stallone',
      'Jean-Claude Van Damme',
      'Arnold Schwarzenegger',
      'Bruce Willis']],
      ['Which actor plays the title character in "The Terminator"?',
      ['Sylvester Stallone',
      'Jean-Claude Van Damme',
      'Arnold Schwarzenegger',
      'Bruce Willis']],
      ['¿Qué actor interpreta al personaje titular en "Terminator"?',
      ['Sylvester Stallone',
      'Jean-Claude Van Damme',
      'Arnold Schwarzenegger',
      'Bruce Willis']]),
    oscar('039', 3, 3, 2017,
      ['La La Land',
      'A Chegada',
      'Lion: Uma Jornada para Casa',
      'Moonlight: Sob a Luz do Luar'],
      ['La La Land',
      'Arrival',
      'Lion',
      'Moonlight'],
      ['La La Land',
      'La llegada',
      'Lion',
      'Moonlight']),
    diretor('040', 3, 0,
      ['12 Homens e uma Sentença',
      '12 Angry Men',
      '12 hombres sin piedad'],
      ['Sidney Lumet',
      'Elia Kazan',
      'William Wyler',
      'George Cukor']),
    q('041', 2, 1,
      ['Em qual país se passa "A Noviça Rebelde"?',
      ['Suíça',
      'Áustria',
      'Alemanha',
      'Hungria']],
      ['In which country is "The Sound of Music" set?',
      ['Switzerland',
      'Austria',
      'Germany',
      'Hungary']],
      ['¿En qué país transcurre "La novicia rebelde"?',
      ['Suiza',
      'Austria',
      'Alemania',
      'Hungría']]),
    diretor('042', 1, 2,
      ['E.T. - O Extraterrestre',
      'E.T. the Extra-Terrestrial',
      'E.T., el extraterrestre'],
      ['Ron Howard',
      'Tim Burton',
      'Steven Spielberg',
      'Robert Zemeckis']),
    q('043', 2, 3,
      ['Qual ator interpreta Tony Stark, o Homem de Ferro, nos filmes da Marvel?',
      ['Chris Evans',
      'Chris Hemsworth',
      'Mark Ruffalo',
      'Robert Downey Jr.']],
      ['Which actor plays Tony Stark, Iron Man, in the Marvel films?',
      ['Chris Evans',
      'Chris Hemsworth',
      'Mark Ruffalo',
      'Robert Downey Jr.']],
      ['¿Qué actor interpreta a Tony Stark, Iron Man, en las películas de Marvel?',
      ['Chris Evans',
      'Chris Hemsworth',
      'Mark Ruffalo',
      'Robert Downey Jr.']]),
    oscar('044', 2, 0, 2002,
      ['Uma Mente Brilhante',
      'Moulin Rouge!',
      'O Senhor dos Anéis: A Sociedade do Anel',
      'Gosford Park'],
      ['A Beautiful Mind',
      'Moulin Rouge!',
      'The Lord of the Rings: The Fellowship of the Ring',
      'Gosford Park'],
      ['Una mente maravillosa',
      'Moulin Rouge!',
      'El señor de los anillos: La comunidad del anillo',
      'Gosford Park']),
    diretor('045', 3, 1,
      ['Princesa Mononoke',
      'Princess Mononoke',
      'La princesa Mononoke'],
      ['Katsuhiro Otomo',
      'Hayao Miyazaki',
      'Makoto Shinkai',
      'Yoshifumi Kondō']),
    q('046', 2, 2,
      ['Em que ano o primeiro filme de Star Wars estreou nos cinemas?',
      ['1975',
      '1976',
      '1977',
      '1978']],
      ['In which year was the first Star Wars film released in theaters?',
      ['1975',
      '1976',
      '1977',
      '1978']],
      ['¿En qué año se estrenó en cines la primera película de Star Wars?',
      ['1975',
      '1976',
      '1977',
      '1978']]),
    diretor('047', 2, 3,
      ['Os Vingadores',
      'The Avengers',
      'Los Vengadores'],
      ['Jon Favreau',
      'James Gunn',
      'Taika Waititi',
      'Joss Whedon']),
    q('048', 3, 0,
      ['Em que ano estreou "Toy Story", o primeiro longa-metragem totalmente animado por computador?',
      ['1995',
      '1996',
      '1998',
      '2000']],
      ['In which year was "Toy Story", the first fully computer-animated feature film, released?',
      ['1995',
      '1996',
      '1998',
      '2000']],
      ['¿En qué año se estrenó "Toy Story", el primer largometraje totalmente animado por computadora?',
      ['1995',
      '1996',
      '1998',
      '2000']]),
    diretor('049', 2, 1,
      ['De Volta para o Futuro',
      'Back to the Future',
      'Volver al futuro'],
      ['Ron Howard',
      'Robert Zemeckis',
      'Ivan Reitman',
      'Richard Donner']),
    q('050', 1, 2,
      ['Qual vilão enfrenta Batman em "O Cavaleiro das Trevas"?',
      ['Bane',
      'Pinguim',
      'Coringa',
      'Duas-Caras']],
      ['Which villain faces Batman in "The Dark Knight"?',
      ['Bane',
      'Penguin',
      'Joker',
      'Two-Face']],
      ['¿Qué villano se enfrenta a Batman en "El caballero de la noche"?',
      ['Bane',
      'Pingüino',
      'Joker',
      'Dos Caras']]),
    q('051', 1, 3,
      ['Qual emoção é a personagem principal de "Divertida Mente"?',
      ['Medo',
      'Tristeza',
      'Raiva',
      'Alegria']],
      ['Which emotion is the main character in "Inside Out"?',
      ['Fear',
      'Sadness',
      'Anger',
      'Joy']],
      ['¿Qué emoción es el personaje principal de "Intensa-Mente"?',
      ['Miedo',
      'Tristeza',
      'Furia',
      'Alegría']]),
    oscar('052', 2, 0, 2007,
      ['Os Infiltrados',
      'Babel',
      'Cartas de Iwo Jima',
      'Pequena Miss Sunshine'],
      ['The Departed',
      'Babel',
      'Letters from Iwo Jima',
      'Little Miss Sunshine'],
      ['Los infiltrados',
      'Babel',
      'Cartas desde Iwo Jima',
      'Pequeña Miss Sunshine']),
    diretor('053', 3, 1,
      ['O Tigre e o Dragão',
      'Crouching Tiger, Hidden Dragon',
      'Tigre y dragón'],
      ['Zhang Yimou',
      'Ang Lee',
      'Wong Kar-wai',
      'Chen Kaige']),
    q('054', 1, 2,
      ['Qual ator interpreta Rocky Balboa no primeiro filme da série?',
      ['Al Pacino',
      'Robert De Niro',
      'Sylvester Stallone',
      'Marlon Brando']],
      ['Which actor plays Rocky Balboa in the first film of the series?',
      ['Al Pacino',
      'Robert De Niro',
      'Sylvester Stallone',
      'Marlon Brando']],
      ['¿Qué actor interpreta a Rocky Balboa en la primera película de la serie?',
      ['Al Pacino',
      'Robert De Niro',
      'Sylvester Stallone',
      'Marlon Brando']]),
    oscar('055', 2, 3, 2013,
      ['Lincoln',
      'As Aventuras de Pi',
      'O Lado Bom da Vida',
      'Argo'],
      ['Lincoln',
      'Life of Pi',
      'Silver Linings Playbook',
      'Argo'],
      ['Lincoln',
      'La vida de Pi',
      'El lado bueno de las cosas',
      'Argo']),
    diretor('056', 3, 0,
      ['O Show de Truman',
      'The Truman Show',
      'El show de Truman'],
      ['Peter Weir',
      'M. Night Shyamalan',
      'Spike Jonze',
      'Michel Gondry']),
    diretor('057', 2, 1,
      ['O Grande Hotel Budapeste',
      'The Grand Budapest Hotel',
      'El gran hotel Budapest'],
      ['Noah Baumbach',
      'Wes Anderson',
      'Sofia Coppola',
      'Greta Gerwig']),
    q('058', 3, 2,
      ['Quem dirigiu "Cidadão Kane"?',
      ['Alfred Hitchcock',
      'John Huston',
      'Orson Welles',
      'Frank Capra']],
      ['Who directed "Citizen Kane"?',
      ['Alfred Hitchcock',
      'John Huston',
      'Orson Welles',
      'Frank Capra']],
      ['¿Quién dirigió "El ciudadano Kane"?',
      ['Alfred Hitchcock',
      'John Huston',
      'Orson Welles',
      'Frank Capra']]),
    q('059', 1, 3,
      ['Como se chama a protagonista de "O Mágico de Oz"?',
      ['Glinda',
      'Tia Em',
      'Bruxa Má do Oeste',
      'Dorothy']],
      ['What is the name of the protagonist in "The Wizard of Oz"?',
      ['Glinda',
      'Aunt Em',
      'Wicked Witch of the West',
      'Dorothy']],
      ['¿Cómo se llama la protagonista de "El mago de Oz"?',
      ['Glinda',
      'Tía Em',
      'Bruja Malvada del Oeste',
      'Dorothy']]),
    oscar('060', 2, 0, 2014,
      ['12 Anos de Escravidão',
      'Gravidade',
      'Trapaça',
      'Capitão Phillips'],
      ['12 Years a Slave',
      'Gravity',
      'American Hustle',
      'Captain Phillips'],
      ['12 años de esclavitud',
      'Gravity',
      'American Hustle',
      'Capitán Phillips']),
  ];
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.filmes = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
