'use strict';

/* Quiz -- tema "futebol". Cada pergunta: id estavel, nivel (1 facil,
      2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  function q(id, nivel, certa, pt, en, es) {
    return { id, nivel, certa, pt: [pt[0], pt.slice(1)], en: [en[0], en.slice(1)], es: [es[0], es.slice(1)] };
  }
  const perguntas = [
    q('futebol-001',
      1,
      0,
      ['Qual seleção venceu a Copa do Mundo de 2014?',
      'Alemanha',
      'Argentina',
      'Holanda',
      'Brasil'],
      ['Which national team won the 2014 World Cup?',
      'Germany',
      'Argentina',
      'Netherlands',
      'Brazil'],
      ['¿Qué selección ganó la Copa del Mundo de 2014?',
      'Alemania',
      'Argentina',
      'Países Bajos',
      'Brasil']), q('futebol-002',
      1,
      1,
      ['Quantos jogadores de cada time ficam em campo?',
      '10',
      '11',
      '12',
      '9'],
      ['How many players per team are on the field?',
      '10',
      '11',
      '12',
      '9'],
      ['¿Cuántos jugadores de cada equipo están en el campo?',
      '10',
      '11',
      '12',
      '9']), q('futebol-003',
      1,
      2,
      ['Qual país sediou a Copa do Mundo de 2022?',
      'Rússia',
      'Arábia Saudita',
      'Catar',
      'Emirados Árabes Unidos'],
      ['Which country hosted the 2022 World Cup?',
      'Russia',
      'Saudi Arabia',
      'Qatar',
      'United Arab Emirates'],
      ['¿Qué país fue sede de la Copa del Mundo de 2022?',
      'Rusia',
      'Arabia Saudita',
      'Catar',
      'Emiratos Árabes Unidos']), q('futebol-004',
      1,
      3,
      ['Quantas Copas do Mundo o Brasil tinha vencido até 2022?',
      '3',
      '4',
      '6',
      '5'],
      ['How many World Cups had Brazil won up to 2022?',
      '3',
      '4',
      '6',
      '5'],
      ['¿Cuántas Copas del Mundo había ganado Brasil hasta 2022?',
      '3',
      '4',
      '6',
      '5']), q('futebol-005',
      1,
      0,
      ['Qual país venceu a primeira Copa do Mundo, em 1930?',
      'Uruguai',
      'Argentina',
      'Itália',
      'Brasil'],
      ['Which country won the first World Cup, in 1930?',
      'Uruguay',
      'Argentina',
      'Italy',
      'Brazil'],
      ['¿Qué país ganó la primera Copa del Mundo, en 1930?',
      'Uruguay',
      'Argentina',
      'Italia',
      'Brasil']), q('futebol-006',
      1,
      1,
      ['Qual cartão expulsa um jogador?',
      'Azul',
      'Vermelho',
      'Verde',
      'Branco'],
      ['Which card sends a player off?',
      'Blue',
      'Red',
      'Green',
      'White'],
      ['¿Qué tarjeta expulsa a un jugador?',
      'Azul',
      'Roja',
      'Verde',
      'Blanca']), q('futebol-007',
      1,
      2,
      ['Qual jogador é conhecido como Pelé?',
      'Diego Maradona',
      'Johan Cruyff',
      'Edson Arantes do Nascimento',
      'Franz Beckenbauer'],
      ['Which player is known as Pelé?',
      'Diego Maradona',
      'Johan Cruyff',
      'Edson Arantes do Nascimento',
      'Franz Beckenbauer'],
      ['¿Qué jugador es conocido como Pelé?',
      'Diego Maradona',
      'Johan Cruyff',
      'Edson Arantes do Nascimento',
      'Franz Beckenbauer']), q('futebol-008',
      1,
      3,
      ['Qual seleção venceu a Copa do Mundo de 2018?',
      'Croácia',
      'Bélgica',
      'Inglaterra',
      'França'],
      ['Which national team won the 2018 World Cup?',
      'Croatia',
      'Belgium',
      'England',
      'France'],
      ['¿Qué selección ganó la Copa del Mundo de 2018?',
      'Croacia',
      'Bélgica',
      'Inglaterra',
      'Francia']), q('futebol-009',
      1,
      0,
      ['Como se chama a cobrança após uma falta direta?',
      'Tiro livre direto',
      'Tiro de meta',
      'Tiro de canto',
      'Arremesso lateral'],
      ['What is the restart after a direct foul called?',
      'Direct free kick',
      'Goal kick',
      'Corner kick',
      'Throw-in'],
      ['¿Cómo se llama el cobro tras una falta directa?',
      'Tiro libre directo',
      'Saque de meta',
      'Tiro de esquina',
      'Saque de banda']), q('futebol-010',
      1,
      1,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2023?',
      'Inter de Milão',
      'Manchester City',
      'Real Madrid',
      'Bayern de Munique'],
      ['Which club won the 2023 UEFA Champions League?',
      'Inter Milan',
      'Manchester City',
      'Real Madrid',
      'Bayern Munich'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2023?',
      'Inter de Milán',
      'Manchester City',
      'Real Madrid',
      'Bayern de Múnich']), q('futebol-011',
      1,
      2,
      ['Qual seleção venceu a Copa do Mundo de 2002?',
      'Alemanha',
      'Itália',
      'Brasil',
      'França'],
      ['Which national team won the 2002 World Cup?',
      'Germany',
      'Italy',
      'Brazil',
      'France'],
      ['¿Qué selección ganó la Copa del Mundo de 2002?',
      'Alemania',
      'Italia',
      'Brasil',
      'Francia']), q('futebol-012',
      1,
      3,
      ['Em que área o goleiro pode usar as mãos?',
      'No campo inteiro',
      'No círculo central',
      'No campo adversário',
      'Na própria área penal'],
      ['In which area may the goalkeeper use their hands?',
      'The entire field',
      'The center circle',
      "The opponent's half",
      'Their own penalty area'],
      ['¿En qué zona puede el portero usar las manos?',
      'Todo el campo',
      'El círculo central',
      'El campo rival',
      'Su propia área penal']), q('futebol-013',
      1,
      0,
      ['Qual seleção venceu a Copa do Mundo de 2010?',
      'Espanha',
      'Holanda',
      'Alemanha',
      'Uruguai'],
      ['Which national team won the 2010 World Cup?',
      'Spain',
      'Netherlands',
      'Germany',
      'Uruguay'],
      ['¿Qué selección ganó la Copa del Mundo de 2010?',
      'España',
      'Países Bajos',
      'Alemania',
      'Uruguay']), q('futebol-014',
      1,
      1,
      ['Qual país venceu a Copa do Mundo de 1998?',
      'Brasil',
      'França',
      'Croácia',
      'Argentina'],
      ['Which country won the 1998 World Cup?',
      'Brazil',
      'France',
      'Croatia',
      'Argentina'],
      ['¿Qué país ganó la Copa del Mundo de 1998?',
      'Brasil',
      'Francia',
      'Croacia',
      'Argentina']), q('futebol-015',
      1,
      2,
      ['Quantos minutos dura uma partida regulamentar, sem acréscimos?',
      '80',
      '100',
      '90',
      '120'],
      ['How many minutes does a regulation match last, excluding added time?',
      '80',
      '100',
      '90',
      '120'],
      ['¿Cuántos minutos dura un partido reglamentario, sin tiempo añadido?',
      '80',
      '100',
      '90',
      '120']), q('futebol-016',
      1,
      3,
      ['Qual país venceu a Copa do Mundo de 2006?',
      'França',
      'Alemanha',
      'Portugal',
      'Itália'],
      ['Which country won the 2006 World Cup?',
      'France',
      'Germany',
      'Portugal',
      'Italy'],
      ['¿Qué país ganó la Copa del Mundo de 2006?',
      'Francia',
      'Alemania',
      'Portugal',
      'Italia']), q('futebol-017',
      1,
      0,
      ['Como se chama a reinicialização pela linha lateral?',
      'Arremesso lateral',
      'Tiro de meta',
      'Tiro de canto',
      'Bola ao chão'],
      ['What is the restart over the touchline called?',
      'Throw-in',
      'Goal kick',
      'Corner kick',
      'Dropped ball'],
      ['¿Cómo se llama la reanudación por la línea lateral?',
      'Saque de banda',
      'Saque de meta',
      'Tiro de esquina',
      'Balón a tierra']), q('futebol-018',
      1,
      1,
      ['Quem marcou na final da Copa do Mundo de 2014?',
      'Thomas Müller',
      'Mario Götze',
      'Miroslav Klose',
      'Toni Kroos'],
      ['Who scored in the 2014 World Cup final?',
      'Thomas Müller',
      'Mario Götze',
      'Miroslav Klose',
      'Toni Kroos'],
      ['¿Quién marcó en la final de la Copa del Mundo de 2014?',
      'Thomas Müller',
      'Mario Götze',
      'Miroslav Klose',
      'Toni Kroos']), q('futebol-019',
      1,
      2,
      ['Qual seleção venceu a Copa do Mundo de 1986?',
      'Alemanha Ocidental',
      'Brasil',
      'Argentina',
      'França'],
      ['Which national team won the 1986 World Cup?',
      'West Germany',
      'Brazil',
      'Argentina',
      'France'],
      ['¿Qué selección ganó la Copa del Mundo de 1986?',
      'Alemania Occidental',
      'Brasil',
      'Argentina',
      'Francia']), q('futebol-020',
      1,
      3,
      ['Qual seleção venceu a Copa do Mundo de 2022?',
      'França',
      'Croácia',
      'Marrocos',
      'Argentina'],
      ['Which national team won the 2022 World Cup?',
      'France',
      'Croatia',
      'Morocco',
      'Argentina'],
      ['¿Qué selección ganó la Copa del Mundo de 2022?',
      'Francia',
      'Croacia',
      'Marruecos',
      'Argentina']), q('futebol-021',
      2,
      0,
      ['Qual clube tinha mais títulos da Liga dos Campeões da UEFA até 2023?',
      'Real Madrid',
      'Milan',
      'Barcelona',
      'Bayern de Munique'],
      ['Which club had the most UEFA Champions League titles up to 2023?',
      'Real Madrid',
      'Milan',
      'Barcelona',
      'Bayern Munich'],
      ['¿Qué club tenía más títulos de la Liga de Campeones de la UEFA hasta 2023?',
      'Real Madrid',
      'Milan',
      'Barcelona',
      'Bayern de Múnich']), q('futebol-022',
      2,
      1,
      ['Quem foi o artilheiro da Copa do Mundo de 2014?',
      'Thomas Müller',
      'James Rodríguez',
      'Neymar',
      'Lionel Messi'],
      ['Who was the top scorer at the 2014 World Cup?',
      'Thomas Müller',
      'James Rodríguez',
      'Neymar',
      'Lionel Messi'],
      ['¿Quién fue el máximo goleador de la Copa del Mundo de 2014?',
      'Thomas Müller',
      'James Rodríguez',
      'Neymar',
      'Lionel Messi']), q('futebol-023',
      2,
      2,
      ['Quem marcou o gol da “Mão de Deus” em 1986?',
      'Pelé',
      'Zico',
      'Diego Maradona',
      'Johan Cruyff'],
      ['Who scored the “Hand of God” goal in 1986?',
      'Pelé',
      'Zico',
      'Diego Maradona',
      'Johan Cruyff'],
      ['¿Quién marcó el gol de la “Mano de Dios” en 1986?',
      'Pelé',
      'Zico',
      'Diego Maradona',
      'Johan Cruyff']), q('futebol-024',
      2,
      3,
      ['Qual seleção venceu a Eurocopa de 2016?',
      'França',
      'Alemanha',
      'Espanha',
      'Portugal'],
      ['Which national team won UEFA Euro 2016?',
      'France',
      'Germany',
      'Spain',
      'Portugal'],
      ['¿Qué selección ganó la Eurocopa de 2016?',
      'Francia',
      'Alemania',
      'España',
      'Portugal']), q('futebol-025',
      2,
      0,
      ['Qual jogador ganhou a Bola de Ouro de 2022?',
      'Karim Benzema',
      'Sadio Mané',
      'Kevin De Bruyne',
      'Robert Lewandowski'],
      ["Which player won the 2022 Ballon d'Or?",
      'Karim Benzema',
      'Sadio Mané',
      'Kevin De Bruyne',
      'Robert Lewandowski'],
      ['¿Qué jugador ganó el Balón de Oro de 2022?',
      'Karim Benzema',
      'Sadio Mané',
      'Kevin De Bruyne',
      'Robert Lewandowski']), q('futebol-026',
      2,
      1,
      ['Em que país foi disputada a Copa do Mundo de 1994?',
      'México',
      'Estados Unidos',
      'Itália',
      'Alemanha'],
      ['In which country was the 1994 World Cup played?',
      'Mexico',
      'United States',
      'Italy',
      'Germany'],
      ['¿En qué país se disputó la Copa del Mundo de 1994?',
      'México',
      'Estados Unidos',
      'Italia',
      'Alemania']), q('futebol-027',
      2,
      2,
      ['Qual clube venceu a primeira Copa dos Campeões Europeus, em 1956?',
      'Milan',
      'Benfica',
      'Real Madrid',
      'Barcelona'],
      ['Which club won the first European Cup, in 1956?',
      'Milan',
      'Benfica',
      'Real Madrid',
      'Barcelona'],
      ['¿Qué club ganó la primera Copa de Europa, en 1956?',
      'Milan',
      'Benfica',
      'Real Madrid',
      'Barcelona']), q('futebol-028',
      2,
      3,
      ['Qual seleção venceu a Copa América de 2021?',
      'Brasil',
      'Uruguai',
      'Colômbia',
      'Argentina'],
      ['Which national team won the 2021 Copa América?',
      'Brazil',
      'Uruguay',
      'Colombia',
      'Argentina'],
      ['¿Qué selección ganó la Copa América de 2021?',
      'Brasil',
      'Uruguay',
      'Colombia',
      'Argentina']), q('futebol-029',
      2,
      0,
      ['Quem treinou a Espanha campeã da Copa do Mundo de 2010?',
      'Vicente del Bosque',
      'Luis Aragonés',
      'Xavi Hernández',
      'Pep Guardiola'],
      ['Who coached Spain when it won the 2010 World Cup?',
      'Vicente del Bosque',
      'Luis Aragonés',
      'Xavi Hernández',
      'Pep Guardiola'],
      ['¿Quién entrenó a España campeona de la Copa del Mundo de 2010?',
      'Vicente del Bosque',
      'Luis Aragonés',
      'Xavi Hernández',
      'Pep Guardiola']), q('futebol-030',
      2,
      1,
      ['Qual país sediou a Copa do Mundo de 1990?',
      'Espanha',
      'Itália',
      'França',
      'México'],
      ['Which country hosted the 1990 World Cup?',
      'Spain',
      'Italy',
      'France',
      'Mexico'],
      ['¿Qué país fue sede de la Copa del Mundo de 1990?',
      'España',
      'Italia',
      'Francia',
      'México']), q('futebol-031',
      2,
      2,
      ['Quem marcou três gols na final da Copa do Mundo de 1966?',
      'Bobby Charlton',
      'Martin Peters',
      'Geoff Hurst',
      'Bobby Moore'],
      ['Who scored three goals in the 1966 World Cup final?',
      'Bobby Charlton',
      'Martin Peters',
      'Geoff Hurst',
      'Bobby Moore'],
      ['¿Quién marcó tres goles en la final de la Copa del Mundo de 1966?',
      'Bobby Charlton',
      'Martin Peters',
      'Geoff Hurst',
      'Bobby Moore']), q('futebol-032',
      2,
      3,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 1999?',
      'Bayern de Munique',
      'Juventus',
      'Barcelona',
      'Manchester United'],
      ['Which club won the 1999 UEFA Champions League?',
      'Bayern Munich',
      'Juventus',
      'Barcelona',
      'Manchester United'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 1999?',
      'Bayern de Múnich',
      'Juventus',
      'Barcelona',
      'Manchester United']), q('futebol-033',
      2,
      0,
      ['Qual seleção venceu a Copa do Mundo de 1974?',
      'Alemanha Ocidental',
      'Holanda',
      'Polônia',
      'Argentina'],
      ['Which national team won the 1974 World Cup?',
      'West Germany',
      'Netherlands',
      'Poland',
      'Argentina'],
      ['¿Qué selección ganó la Copa del Mundo de 1974?',
      'Alemania Occidental',
      'Países Bajos',
      'Polonia',
      'Argentina']), q('futebol-034',
      2,
      1,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2005?',
      'Milan',
      'Liverpool',
      'Chelsea',
      'Manchester United'],
      ['Which club won the 2005 UEFA Champions League?',
      'Milan',
      'Liverpool',
      'Chelsea',
      'Manchester United'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2005?',
      'Milan',
      'Liverpool',
      'Chelsea',
      'Manchester United']), q('futebol-035',
      2,
      2,
      ['Qual país venceu a Copa do Mundo de 1966?',
      'Alemanha Ocidental',
      'Portugal',
      'Inglaterra',
      'União Soviética'],
      ['Which country won the 1966 World Cup?',
      'West Germany',
      'Portugal',
      'England',
      'Soviet Union'],
      ['¿Qué país ganó la Copa del Mundo de 1966?',
      'Alemania Occidental',
      'Portugal',
      'Inglaterra',
      'Unión Soviética']), q('futebol-036',
      2,
      3,
      ['Quem foi o capitão da Itália campeã da Copa do Mundo de 2006?',
      'Andrea Pirlo',
      'Francesco Totti',
      'Gianluigi Buffon',
      'Fabio Cannavaro'],
      ['Who captained Italy when it won the 2006 World Cup?',
      'Andrea Pirlo',
      'Francesco Totti',
      'Gianluigi Buffon',
      'Fabio Cannavaro'],
      ['¿Quién fue el capitán de Italia campeona de la Copa del Mundo de 2006?',
      'Andrea Pirlo',
      'Francesco Totti',
      'Gianluigi Buffon',
      'Fabio Cannavaro']), q('futebol-037',
      2,
      0,
      ['Qual seleção venceu a Eurocopa de 2004?',
      'Grécia',
      'Portugal',
      'República Tcheca',
      'França'],
      ['Which national team won UEFA Euro 2004?',
      'Greece',
      'Portugal',
      'Czech Republic',
      'France'],
      ['¿Qué selección ganó la Eurocopa de 2004?',
      'Grecia',
      'Portugal',
      'República Checa',
      'Francia']), q('futebol-038',
      2,
      1,
      ['Qual país sediou a Copa do Mundo de 2002 junto com a Coreia do Sul?',
      'China',
      'Japão',
      'Austrália',
      'Tailândia'],
      ['Which country co-hosted the 2002 World Cup with South Korea?',
      'China',
      'Japan',
      'Australia',
      'Thailand'],
      ['¿Qué país fue sede de la Copa del Mundo de 2002 junto con Corea del Sur?',
      'China',
      'Japón',
      'Australia',
      'Tailandia']), q('futebol-039',
      2,
      2,
      ['Qual jogador ganhou a Bola de Ouro de 1995?',
      'Roberto Baggio',
      'Jari Litmanen',
      'George Weah',
      'Ronaldo'],
      ["Which player won the 1995 Ballon d'Or?",
      'Roberto Baggio',
      'Jari Litmanen',
      'George Weah',
      'Ronaldo'],
      ['¿Qué jugador ganó el Balón de Oro de 1995?',
      'Roberto Baggio',
      'Jari Litmanen',
      'George Weah',
      'Ronaldo']), q('futebol-040',
      2,
      3,
      ['Qual seleção venceu a Copa do Mundo de 1978?',
      'Holanda',
      'Brasil',
      'Itália',
      'Argentina'],
      ['Which national team won the 1978 World Cup?',
      'Netherlands',
      'Brazil',
      'Italy',
      'Argentina'],
      ['¿Qué selección ganó la Copa del Mundo de 1978?',
      'Países Bajos',
      'Brasil',
      'Italia',
      'Argentina']), q('futebol-041',
      2,
      0,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2012?',
      'Chelsea',
      'Bayern de Munique',
      'Barcelona',
      'Real Madrid'],
      ['Which club won the 2012 UEFA Champions League?',
      'Chelsea',
      'Bayern Munich',
      'Barcelona',
      'Real Madrid'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2012?',
      'Chelsea',
      'Bayern de Múnich',
      'Barcelona',
      'Real Madrid']), q('futebol-042',
      2,
      1,
      ['Quem marcou na final da Copa do Mundo de 2010?',
      'David Villa',
      'Andrés Iniesta',
      'Xavi',
      'Fernando Torres'],
      ['Who scored in the 2010 World Cup final?',
      'David Villa',
      'Andrés Iniesta',
      'Xavi',
      'Fernando Torres'],
      ['¿Quién marcó en la final de la Copa del Mundo de 2010?',
      'David Villa',
      'Andrés Iniesta',
      'Xavi',
      'Fernando Torres']), q('futebol-043',
      2,
      2,
      ['Qual seleção venceu a Copa do Mundo de 1958?',
      'Suécia',
      'França',
      'Brasil',
      'Alemanha Ocidental'],
      ['Which national team won the 1958 World Cup?',
      'Sweden',
      'France',
      'Brazil',
      'West Germany'],
      ['¿Qué selección ganó la Copa del Mundo de 1958?',
      'Suecia',
      'Francia',
      'Brasil',
      'Alemania Occidental']), q('futebol-044',
      2,
      3,
      ['Qual país sediou a Copa do Mundo de 1970?',
      'Argentina',
      'Brasil',
      'Itália',
      'México'],
      ['Which country hosted the 1970 World Cup?',
      'Argentina',
      'Brazil',
      'Italy',
      'Mexico'],
      ['¿Qué país fue sede de la Copa del Mundo de 1970?',
      'Argentina',
      'Brasil',
      'Italia',
      'México']), q('futebol-045',
      2,
      0,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2019?',
      'Liverpool',
      'Tottenham Hotspur',
      'Ajax',
      'Barcelona'],
      ['Which club won the 2019 UEFA Champions League?',
      'Liverpool',
      'Tottenham Hotspur',
      'Ajax',
      'Barcelona'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2019?',
      'Liverpool',
      'Tottenham Hotspur',
      'Ajax',
      'Barcelona']), q('futebol-046',
      3,
      1,
      ['Quem era o maior artilheiro das Copas do Mundo masculinas até 2022?',
      'Ronaldo',
      'Miroslav Klose',
      'Gerd Müller',
      'Pelé'],
      ["Who was the all-time top scorer in men's World Cups up to 2022?",
      'Ronaldo',
      'Miroslav Klose',
      'Gerd Müller',
      'Pelé'],
      ['¿Quién era el máximo goleador histórico de las Copas del Mundo masculinas hasta 2022?',
      'Ronaldo',
      'Miroslav Klose',
      'Gerd Müller',
      'Pelé']), q('futebol-047',
      3,
      2,
      ['Qual seleção venceu a Copa do Mundo de 1934?',
      'Tchecoslováquia',
      'Alemanha',
      'Itália',
      'Áustria'],
      ['Which national team won the 1934 World Cup?',
      'Czechoslovakia',
      'Germany',
      'Italy',
      'Austria'],
      ['¿Qué selección ganó la Copa del Mundo de 1934?',
      'Checoslovaquia',
      'Alemania',
      'Italia',
      'Austria']), q('futebol-048',
      3,
      3,
      ['Qual país sediou a Copa do Mundo de 1962?',
      'Argentina',
      'Brasil',
      'Uruguai',
      'Chile'],
      ['Which country hosted the 1962 World Cup?',
      'Argentina',
      'Brazil',
      'Uruguay',
      'Chile'],
      ['¿Qué país fue sede de la Copa del Mundo de 1962?',
      'Argentina',
      'Brasil',
      'Uruguay',
      'Chile']), q('futebol-049',
      3,
      0,
      ['Qual seleção venceu a Copa do Mundo de 1954?',
      'Alemanha Ocidental',
      'Hungria',
      'Áustria',
      'Uruguai'],
      ['Which national team won the 1954 World Cup?',
      'West Germany',
      'Hungary',
      'Austria',
      'Uruguay'],
      ['¿Qué selección ganó la Copa del Mundo de 1954?',
      'Alemania Occidental',
      'Hungría',
      'Austria',
      'Uruguay']), q('futebol-050',
      3,
      1,
      ['Qual clube venceu a Copa dos Campeões Europeus de 1967?',
      'Inter de Milão',
      'Celtic',
      'Real Madrid',
      'Benfica'],
      ['Which club won the 1967 European Cup?',
      'Inter Milan',
      'Celtic',
      'Real Madrid',
      'Benfica'],
      ['¿Qué club ganó la Copa de Europa de 1967?',
      'Inter de Milán',
      'Celtic',
      'Real Madrid',
      'Benfica']), q('futebol-051',
      3,
      2,
      ['Qual jogador ganhou a Bola de Ouro de 1986?',
      'Gary Lineker',
      'Diego Maradona',
      'Igor Belanov',
      'Michel Platini'],
      ["Which player won the 1986 Ballon d'Or?",
      'Gary Lineker',
      'Diego Maradona',
      'Igor Belanov',
      'Michel Platini'],
      ['¿Qué jugador ganó el Balón de Oro de 1986?',
      'Gary Lineker',
      'Diego Maradona',
      'Igor Belanov',
      'Michel Platini']), q('futebol-052',
      3,
      3,
      ['Qual seleção venceu a Copa do Mundo de 1938?',
      'Hungria',
      'Brasil',
      'Suécia',
      'Itália'],
      ['Which national team won the 1938 World Cup?',
      'Hungary',
      'Brazil',
      'Sweden',
      'Italy'],
      ['¿Qué selección ganó la Copa del Mundo de 1938?',
      'Hungría',
      'Brasil',
      'Suecia',
      'Italia']), q('futebol-053',
      3,
      0,
      ['Qual clube venceu a Copa dos Campeões Europeus de 1979?',
      'Nottingham Forest',
      'Malmö',
      'Liverpool',
      'Hamburgo'],
      ['Which club won the 1979 European Cup?',
      'Nottingham Forest',
      'Malmö',
      'Liverpool',
      'Hamburg'],
      ['¿Qué club ganó la Copa de Europa de 1979?',
      'Nottingham Forest',
      'Malmö',
      'Liverpool',
      'Hamburgo']), q('futebol-054',
      3,
      1,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2001?',
      'Valencia',
      'Bayern de Munique',
      'Real Madrid',
      'Manchester United'],
      ['Which club won the 2001 UEFA Champions League?',
      'Valencia',
      'Bayern Munich',
      'Real Madrid',
      'Manchester United'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2001?',
      'Valencia',
      'Bayern de Múnich',
      'Real Madrid',
      'Manchester United']), q('futebol-055',
      3,
      2,
      ['Qual seleção venceu a Copa do Mundo de 1950?',
      'Brasil',
      'Suécia',
      'Uruguai',
      'Espanha'],
      ['Which national team won the 1950 World Cup?',
      'Brazil',
      'Sweden',
      'Uruguay',
      'Spain'],
      ['¿Qué selección ganó la Copa del Mundo de 1950?',
      'Brasil',
      'Suecia',
      'Uruguay',
      'España']), q('futebol-056',
      3,
      3,
      ['Qual clube venceu a Liga dos Campeões da UEFA de 2004?',
      'Monaco',
      'Chelsea',
      'Deportivo La Coruña',
      'Porto'],
      ['Which club won the 2004 UEFA Champions League?',
      'Monaco',
      'Chelsea',
      'Deportivo La Coruña',
      'Porto'],
      ['¿Qué club ganó la Liga de Campeones de la UEFA de 2004?',
      'Monaco',
      'Chelsea',
      'Deportivo La Coruña',
      'Porto']), q('futebol-057',
      3,
      0,
      ['Qual seleção venceu a Eurocopa de 1992?',
      'Dinamarca',
      'Alemanha',
      'Holanda',
      'França'],
      ['Which national team won UEFA Euro 1992?',
      'Denmark',
      'Germany',
      'Netherlands',
      'France'],
      ['¿Qué selección ganó la Eurocopa de 1992?',
      'Dinamarca',
      'Alemania',
      'Países Bajos',
      'Francia']), q('futebol-058',
      3,
      1,
      ['Qual jogador ganhou a Bola de Ouro de 1963?',
      'Ferenc Puskás',
      'Lev Yashin',
      'Eusébio',
      'Bobby Charlton'],
      ["Which player won the 1963 Ballon d'Or?",
      'Ferenc Puskás',
      'Lev Yashin',
      'Eusébio',
      'Bobby Charlton'],
      ['¿Qué jugador ganó el Balón de Oro de 1963?',
      'Ferenc Puskás',
      'Lev Yashin',
      'Eusébio',
      'Bobby Charlton']), q('futebol-059',
      3,
      2,
      ['Qual clube venceu a Copa dos Campeões Europeus de 1982?',
      'Bayern de Munique',
      'Hamburgo',
      'Aston Villa',
      'Benfica'],
      ['Which club won the 1982 European Cup?',
      'Bayern Munich',
      'Hamburg',
      'Aston Villa',
      'Benfica'],
      ['¿Qué club ganó la Copa de Europa de 1982?',
      'Bayern de Múnich',
      'Hamburgo',
      'Aston Villa',
      'Benfica']), q('futebol-060',
      3,
      3,
      ['Qual seleção venceu a Copa do Mundo de 1982?',
      'Alemanha Ocidental',
      'Polônia',
      'França',
      'Itália'],
      ['Which national team won the 1982 World Cup?',
      'West Germany',
      'Poland',
      'France',
      'Italy'],
      ['¿Qué selección ganó la Copa del Mundo de 1982?',
      'Alemania Occidental',
      'Polonia',
      'Francia',
      'Italia']),
  ];
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.futebol = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
