'use strict';

/* Quiz -- tema "games". Cada pergunta: id estavel, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  function q(id, nivel, certa, textos, alternativas) {
    return {
      id, nivel, certa,
      pt: [textos[0], alternativas],
      en: [textos[1], alternativas],
      es: [textos[2], alternativas],
    };
  }

  const perguntas = [
    q('games-001', 1, 0, ['Qual encanador é o mascote da Nintendo?',
      "Which plumber is Nintendo's mascot?", '¿Qué fontanero es la mascota de Nintendo?'],
    ['Mario', 'Luigi', 'Wario', 'Toad']),
    q('games-002', 1, 1, ['Em qual jogo aparecem monstros verdes chamados Creepers?',
      'In which game do green monsters called Creepers appear?',
      '¿En qué juego aparecen monstruos verdes llamados Creepers?'],
    ['Roblox', 'Minecraft', 'Terraria', 'Fortnite']),
    q('games-003', 1, 2, ['Qual é o nome do herói da série The Legend of Zelda?',
      'What is the name of the hero of The Legend of Zelda series?',
      '¿Cómo se llama el héroe de la serie The Legend of Zelda?'],
    ['Zelda', 'Ganon', 'Link', 'Epona']),
    q('games-004', 1, 3, ['Qual empresa criou o console PlayStation?',
      'Which company created the PlayStation console?', '¿Qué empresa creó la consola PlayStation?'],
    ['Sega', 'Microsoft', 'Atari', 'Sony']),
    q('games-005', 1, 0, ['Qual personagem é o mascote da série Sonic the Hedgehog?',
      'Which character is the mascot of the Sonic the Hedgehog series?',
      '¿Qué personaje es la mascota de la serie Sonic the Hedgehog?'],
    ['Sonic', 'Tails', 'Knuckles', 'Shadow']),
    q('games-006', 1, 1, ['Em qual jogo os tripulantes tentam descobrir quem é o impostor?',
      'In which game do crewmates try to find out who the impostor is?',
      '¿En qué juego los tripulantes intentan descubrir quién es el impostor?'],
    ['Fortnite', 'Among Us', 'Roblox', 'Overwatch']),
    q('games-007', 1, 2, ['Qual empresa desenvolveu a série de jogos Pokémon?',
      'Which company developed the Pokémon game series?', '¿Qué empresa desarrolló la serie de juegos Pokémon?'],
    ['Capcom', 'Square Enix', 'Game Freak', 'Konami']),
    q('games-008', 1, 3, ['Qual destes é um console portátil da Nintendo?',
      'Which of these is a Nintendo handheld console?', '¿Cuál de estas es una consola portátil de Nintendo?'],
    ['PlayStation Vita', 'Game Gear', 'Steam Deck', 'Nintendo Switch Lite']),
    q('games-009', 1, 0, ['Qual personagem usa um martelo em Donkey Kong?',
      'Which character uses a hammer in Donkey Kong?', '¿Qué personaje usa un martillo en Donkey Kong?'],
    ['Mario', 'Link', 'Kirby', 'Samus']),
    q('games-010', 1, 1, ['Em qual série aparece o personagem Master Chief?',
      'In which series does the character Master Chief appear?', '¿En qué serie aparece el personaje Master Chief?'],
    ['Gears of War', 'Halo', 'Doom', 'Mass Effect']),
    q('games-011', 1, 2, ['Qual cor tem o fantasma Blinky no Pac-Man clássico?',
      'What color is Blinky in classic Pac-Man?', '¿De qué color es Blinky en el Pac-Man clásico?'],
    ['Azul', 'Rosa', 'Vermelho', 'Laranja']),
    q('games-012', 1, 3, ['Qual jogo de corrida é estrelado por Mario e seus amigos?',
      'Which racing game stars Mario and his friends?', '¿Qué juego de carreras protagonizan Mario y sus amigos?'],
    ['F-Zero', 'Gran Turismo', 'Forza Motorsport', 'Mario Kart']),
    q('games-013', 1, 0, ['Qual personagem principal aparece na série Tomb Raider?',
      'Which main character appears in the Tomb Raider series?',
      '¿Qué personaje principal aparece en la serie Tomb Raider?'],
    ['Lara Croft', 'Aloy', 'Jill Valentine', 'Chloe Frazer']),
    q('games-014', 1, 1, ['Qual empresa criou a série de jogos Assassin’s Creed?',
      'Which company created the Assassin’s Creed game series?',
      '¿Qué empresa creó la serie de juegos Assassin’s Creed?'],
    ['EA', 'Ubisoft', 'Rockstar Games', 'Valve']),
    q('games-015', 1, 2, ['Qual jogo de luta reúne personagens de várias franquias da Nintendo?',
      'Which fighting game brings together characters from several Nintendo franchises?',
      '¿Qué juego de lucha reúne personajes de varias franquicias de Nintendo?'],
    ['Tekken', 'Street Fighter', 'Super Smash Bros.', 'Mortal Kombat']),
    q('games-016', 1, 3, ['Em qual série aparecem os monstros chamados Pokémon?',
      'In which series do creatures called Pokémon appear?',
      '¿En qué serie aparecen los monstruos llamados Pokémon?'],
    ['Digimon', 'Yo-kai Watch', 'Monster Hunter', 'Pokémon']),
    q('games-017', 1, 0, ['Qual companhia fabrica os consoles Xbox?',
      'Which company makes Xbox consoles?', '¿Qué compañía fabrica las consolas Xbox?'],
    ['Microsoft', 'Sony', 'Nintendo', 'Sega']),
    q('games-018', 1, 1, ['Qual jogo coloca jogadores em uma ilha para construir e conversar com animais?',
      'Which game puts players on an island to build and talk with animals?',
      '¿Qué juego pone a los jugadores en una isla para construir y hablar con animales?'],
    ['Stardew Valley', 'Animal Crossing', 'The Sims', 'Harvest Moon']),
    q('games-019', 1, 2, ['Qual personagem é o protagonista de God of War?',
      'Which character is the protagonist of God of War?', '¿Qué personaje es el protagonista de God of War?'],
    ['Atreus', 'Zeus', 'Kratos', 'Baldur']),
    q('games-020', 1, 3, ['Qual série de jogos apresenta o caçador de demônios Dante?',
      'Which game series features demon hunter Dante?',
      '¿Qué serie de juegos presenta al cazador de demonios Dante?'],
    ['Bayonetta', 'Darksiders', 'Ninja Gaiden', 'Devil May Cry']),
    q('games-021', 2, 0, ['Em que ano foi lançado no Japão o primeiro jogo da série Pokémon?',
      'In what year was the first Pokémon game released in Japan?',
      '¿En qué año se lanzó en Japón el primer juego de la serie Pokémon?'],
    ['1996', '1994', '1998', '2000']),
    q('games-022', 2, 1, ['Quantos fantasmas perseguem o jogador no Pac-Man clássico?',
      'How many ghosts chase the player in classic Pac-Man?',
      '¿Cuántos fantasmas persiguen al jugador en el Pac-Man clásico?'],
    ['3', '4', '5', '6']),
    q('games-023', 2, 2, ['Qual estúdio desenvolveu The Witcher 3: Wild Hunt?',
      'Which studio developed The Witcher 3: Wild Hunt?', '¿Qué estudio desarrolló The Witcher 3: Wild Hunt?'],
    ['BioWare', 'Bethesda Game Studios', 'CD Projekt Red', 'Ubisoft Montreal']),
    q('games-024', 2, 3, ['Qual jogo de quebra-cabeça com peças de quatro blocos foi criado por Alexey Pajitnov?',
      'Which puzzle game with four-block pieces was created by Alexey Pajitnov?',
      '¿Qué juego de rompecabezas con piezas de cuatro bloques creó Alexey Pajitnov?'],
    ['Columns', 'Puyo Puyo', 'Dr. Mario', 'Tetris']),
    q('games-025', 2, 0, ['Qual console da Nintendo, lançado em 2006, usava controle sensível a movimentos?',
      'Which Nintendo console, released in 2006, used a motion-sensing controller?',
      '¿Qué consola de Nintendo, lanzada en 2006, usaba un mando sensible al movimiento?'],
    ['Wii', 'GameCube', 'Nintendo 64', 'Wii U']),
    q('games-026', 2, 1, ['Qual é o protagonista da série Half-Life?',
      'Who is the protagonist of the Half-Life series?', '¿Quién es el protagonista de la serie Half-Life?'],
    ['Duke Nukem', 'Gordon Freeman', 'Marcus Fenix', 'Isaac Clarke']),
    q('games-027', 2, 2, ['Qual empresa criou o primeiro Doom, lançado em 1993?',
      'Which company created the first Doom, released in 1993?',
      '¿Qué empresa creó el primer Doom, lanzado en 1993?'],
    ['Apogee Software', 'Epic MegaGames', 'id Software', 'Sierra On-Line']),
    q('games-028', 2, 3, ['Qual console da Sega é chamado de Genesis na América do Norte?',
      'Which Sega console is called Genesis in North America?',
      '¿Qué consola de Sega se llama Genesis en Norteamérica?'],
    ['Master System', 'Saturn', 'Game Gear', 'Mega Drive']),
    q('games-029', 2, 0, ['Qual estúdio desenvolveu The Elder Scrolls V: Skyrim?',
      'Which studio developed The Elder Scrolls V: Skyrim?',
      '¿Qué estudio desarrolló The Elder Scrolls V: Skyrim?'],
    ['Bethesda Game Studios', 'BioWare', 'Obsidian Entertainment', 'Ubisoft Montreal']),
    q('games-030', 2, 1, ['Em qual jogo o jogador controla o caçador de recompensas Samus Aran?',
      'In which game does the player control bounty hunter Samus Aran?',
      '¿En qué juego controla el jugador a la cazarrecompensas Samus Aran?'],
    ['Star Fox', 'Metroid', 'F-Zero', 'Kid Icarus']),
    q('games-031', 2, 2, ['Qual empresa criou a Unreal Engine?',
      'Which company created Unreal Engine?', '¿Qué empresa creó Unreal Engine?'],
    ['Valve', 'Crytek', 'Epic Games', 'Unity Technologies']),
    q('games-032', 2, 3, ['Qual jogo da Valve é ambientado na cidade fictícia de City 17?',
      'Which Valve game is set in the fictional city of City 17?',
      '¿Qué juego de Valve está ambientado en la ciudad ficticia de City 17?'],
    ['Portal', 'Left 4 Dead', 'Team Fortress 2', 'Half-Life 2']),
    q('games-033', 2, 0, ['Qual personagem é o rival de Mario na maioria dos jogos da série?',
      'Which character is Mario’s rival in most games in the series?',
      '¿Qué personaje es el rival de Mario en la mayoría de los juegos de la serie?'],
    ['Bowser', 'Wario', 'Donkey Kong', 'King Boo']),
    q('games-034', 2, 1, ['Em qual jogo a frase “The cake is a lie” ficou famosa?',
      'In which game did the phrase “The cake is a lie” become famous?',
      '¿En qué juego se hizo famosa la frase “The cake is a lie”?'],
    ['Half-Life 2', 'Portal', 'Bioshock', 'The Stanley Parable']),
    q('games-035', 2, 2, ['Qual foi o primeiro console da Sony, lançado no Japão em 1994?',
      'Which was Sony’s first console, released in Japan in 1994?',
      '¿Cuál fue la primera consola de Sony, lanzada en Japón en 1994?'],
    ['PlayStation 2', 'PlayStation 3', 'PlayStation', 'PlayStation Portable']),
    q('games-036', 2, 3, ['Qual estúdio desenvolveu a série Dark Souls?',
      'Which studio developed the Dark Souls series?', '¿Qué estudio desarrolló la serie Dark Souls?'],
    ['Capcom', 'PlatinumGames', 'Team Ninja', 'FromSoftware']),
    q('games-037', 2, 0, ['Qual jogo de estratégia em tempo real foi criado pela Blizzard em 1994?',
      'Which real-time strategy game was created by Blizzard in 1994?',
      '¿Qué juego de estrategia en tiempo real creó Blizzard en 1994?'],
    ['Warcraft: Orcs & Humans', 'StarCraft', 'Diablo', 'Heroes of the Storm']),
    q('games-038', 2, 1, ['Qual empresa desenvolveu a franquia Gran Turismo?',
      'Which company developed the Gran Turismo franchise?', '¿Qué empresa desarrolló la franquicia Gran Turismo?'],
    ['Turn 10 Studios', 'Polyphony Digital', 'Codemasters', 'Criterion Games']),
    q('games-039', 2, 2, ['Qual série da Capcom apresenta o personagem Ryu?',
      'Which Capcom series features the character Ryu?', '¿Qué serie de Capcom presenta al personaje Ryu?'],
    ['Mega Man', 'Resident Evil', 'Street Fighter', 'Ace Attorney']),
    q('games-040', 2, 3, ['Qual jogo da Rockstar Games se passa na cidade fictícia de Los Santos?',
      'Which Rockstar Games title is set in the fictional city of Los Santos?',
      '¿Qué juego de Rockstar Games transcurre en la ciudad ficticia de Los Santos?'],
    ['Red Dead Redemption', 'Bully', 'Max Payne 3', 'Grand Theft Auto V']),
    q('games-041', 2, 0, ['Qual console da Nintendo introduziu o controle analógico na linha principal?',
      'Which Nintendo console introduced the analog stick to its main console line?',
      '¿Qué consola de Nintendo introdujo el mando analógico en su línea principal?'],
    ['Nintendo 64', 'Super Nintendo', 'GameCube', 'Wii']),
    q('games-042', 2, 1, ['Qual personagem é a protagonista de Horizon Zero Dawn?',
      'Which character is the protagonist of Horizon Zero Dawn?',
      '¿Qué personaje es la protagonista de Horizon Zero Dawn?'],
    ['Ellie', 'Aloy', 'Faith Connors', 'Senua']),
    q('games-043', 2, 2, ['Em qual série aparece o reino de Hyrule?',
      'In which series does the kingdom of Hyrule appear?', '¿En qué serie aparece el reino de Hyrule?'],
    ['Final Fantasy', 'Dragon Quest', 'The Legend of Zelda', 'Fire Emblem']),
    q('games-044', 2, 3, ['Qual jogo foi desenvolvido pela Mojang Studios?',
      'Which game was developed by Mojang Studios?', '¿Qué juego desarrolló Mojang Studios?'],
    ['Terraria', 'Roblox', 'Valheim', 'Minecraft']),
    q('games-045', 2, 0, ['Qual personagem principal aparece na série de jogos Mega Man?',
      'Which main character appears in the Mega Man game series?',
      '¿Qué personaje principal aparece en la serie de juegos Mega Man?'],
    ['Mega Man', 'Proto Man', 'Dr. Wily', 'Bass']),
    q('games-046', 3, 1, ['Qual empresa lançou o console Neo Geo em 1990?',
      'Which company released the Neo Geo console in 1990?', '¿Qué empresa lanzó la consola Neo Geo en 1990?'],
    ['Namco', 'SNK', 'NEC', 'Hudson Soft']),
    q('games-047', 3, 2, ['Qual empresa criou o jogo arcade Space Invaders, de 1978?',
      'Which company created the 1978 arcade game Space Invaders?',
      '¿Qué empresa creó el juego arcade Space Invaders, de 1978?'],
    ['Namco', 'Sega', 'Taito', 'Atari']),
    q('games-048', 3, 3, ['Qual designer criou os personagens de Sonic the Hedgehog?',
      'Which designer created the characters of Sonic the Hedgehog?',
      '¿Qué diseñador creó los personajes de Sonic the Hedgehog?'],
    ['Yu Suzuki', 'Hideo Kojima', 'Shigeru Miyamoto', 'Naoto Ohshima']),
    q('games-049', 3, 0, ['Qual jogo de Nintendo 64 apresentou Banjo e Kazooie em 1998?',
      'Which Nintendo 64 game introduced Banjo and Kazooie in 1998?',
      '¿Qué juego de Nintendo 64 presentó a Banjo y Kazooie en 1998?'],
    ['Banjo-Kazooie', 'Conker’s Bad Fur Day', 'Jet Force Gemini', 'Diddy Kong Racing']),
    q('games-050', 3, 1, ['Qual estúdio desenvolveu Hades, lançado em 2020?',
      'Which studio developed Hades, released in 2020?', '¿Qué estudio desarrolló Hades, lanzado en 2020?'],
    ['Team Cherry', 'Supergiant Games', 'Klei Entertainment', 'Motion Twin']),
    q('games-051', 3, 2, ['Qual jogo de arcade de 1981 popularizou o personagem Donkey Kong?',
      'Which 1981 arcade game popularized the character Donkey Kong?',
      '¿Qué juego arcade de 1981 popularizó al personaje Donkey Kong?'],
    ['Popeye', 'Mario Bros.', 'Donkey Kong', 'Joust']),
    q('games-052', 3, 3, ['Qual console da NEC foi chamado de PC Engine no Japão?',
      'Which NEC console was called PC Engine in Japan?', '¿Qué consola de NEC se llamó PC Engine en Japón?'],
    ['Neo Geo', 'WonderSwan', 'Sega Saturn', 'TurboGrafx-16']),
    q('games-053', 3, 0, ['Qual jogo da Blizzard, lançado em 1998, se passa no setor Koprulu?',
      'Which Blizzard game, released in 1998, is set in the Koprulu Sector?',
      '¿Qué juego de Blizzard, lanzado en 1998, transcurre en el sector Koprulu?'],
    ['StarCraft', 'Warcraft III', 'Diablo II', 'Overwatch']),
    q('games-054', 3, 1, ['Qual compositor criou o tema principal de The Legend of Zelda?',
      'Which composer created the main theme of The Legend of Zelda?',
      '¿Qué compositor creó el tema principal de The Legend of Zelda?'],
    ['Koji Kondo', 'Nobuo Uematsu', 'Yoko Shimomura', 'Yasunori Mitsuda']),
    q('games-055', 3, 2, ['Qual jogo da Valve, de 2007, apresenta a personagem Chell?',
      'Which 2007 Valve game features the character Chell?',
      '¿Qué juego de Valve de 2007 presenta al personaje Chell?'],
    ['Team Fortress 2', 'Half-Life 2: Episode Two', 'Portal', 'Left 4 Dead']),
    q('games-056', 3, 3, ['Qual empresa publicou o primeiro jogo Metal Gear, de 1987?',
      'Which company published the first Metal Gear game, from 1987?',
      '¿Qué empresa publicó el primer juego Metal Gear, de 1987?'],
    ['Capcom', 'Taito', 'SNK', 'Konami']),
    q('games-057', 3, 0, ['Qual estúdio criou o jogo indie Hollow Knight?',
      'Which studio created the indie game Hollow Knight?', '¿Qué estudio creó el juego indie Hollow Knight?'],
    ['Team Cherry', 'Playdead', 'Motion Twin', 'Giant Sparrow']),
    q('games-058', 3, 1, ['Qual jogo de 1985 foi o primeiro da série Super Mario Bros.?',
      'Which 1985 game was the first in the Super Mario Bros. series?',
      '¿Qué juego de 1985 fue el primero de la serie Super Mario Bros.?'],
    ['Mario Bros.', 'Super Mario Bros.', 'Super Mario Bros. 2', 'Super Mario World']),
    q('games-059', 3, 2, ['Qual empresa desenvolveu o console Atari 2600?',
      'Which company developed the Atari 2600 console?', '¿Qué empresa desarrolló la consola Atari 2600?'],
    ['Coleco', 'Mattel', 'Atari', 'Magnavox']),
    q('games-060', 3, 3, ['Qual jogo de 2011 da FromSoftware se passa no reino de Lordran?',
      'Which 2011 FromSoftware game is set in the kingdom of Lordran?',
      '¿Qué juego de FromSoftware de 2011 transcurre en el reino de Lordran?'],
    ['Demon’s Souls', 'Bloodborne', 'Sekiro: Shadows Die Twice', 'Dark Souls']),
  ];

  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.games = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
