'use strict';

/* Quiz -- tema "mundo". Cada pergunta: id estavel, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  const perguntas = [
    { id: 'mundo-001', nivel: 1, certa: 0,
      pt: ['Qual é a capital da França?',
        ['Paris', 'Lyon', 'Marselha', 'Bruxelas']],
      en: ['What is the capital of France?',
        ['Paris', 'Lyon', 'Marseille', 'Brussels']],
      es: ['¿Cuál es la capital de Francia?',
        ['París', 'Lyon', 'Marsella', 'Bruselas']] },
    { id: 'mundo-002', nivel: 1, certa: 1,
      pt: ['Qual é o maior oceano do mundo?',
        ['Atlântico', 'Pacífico', 'Índico', 'Ártico']],
      en: ['What is the largest ocean in the world?',
        ['Atlantic', 'Pacific', 'Indian', 'Arctic']],
      es: ['¿Cuál es el océano más grande del mundo?',
        ['Atlántico', 'Pacífico', 'Índico', 'Ártico']] },
    { id: 'mundo-003', nivel: 1, certa: 2,
      pt: ['Qual é a capital do Japão?',
        ['Osaka', 'Quioto', 'Tóquio', 'Seul']],
      en: ['What is the capital of Japan?',
        ['Osaka', 'Kyoto', 'Tokyo', 'Seoul']],
      es: ['¿Cuál es la capital de Japón?',
        ['Osaka', 'Kioto', 'Tokio', 'Seúl']] },
    { id: 'mundo-004', nivel: 1, certa: 3,
      pt: ['Qual rio atravessa o Egito e deságua no Mar Mediterrâneo?',
        ['Danúbio', 'Tigre', 'Jordão', 'Nilo']],
      en: ['Which river flows through Egypt and empties into the Mediterranean Sea?',
        ['Danube', 'Tigris', 'Jordan', 'Nile']],
      es: ['¿Qué río atraviesa Egipto y desemboca en el mar Mediterráneo?',
        ['Danubio', 'Tigris', 'Jordán', 'Nilo']] },
    { id: 'mundo-005', nivel: 1, certa: 0,
      pt: ['Qual é a montanha mais alta do mundo acima do nível do mar?',
        ['Everest', 'K2', 'Kilimanjaro', 'Mont Blanc']],
      en: ['What is the highest mountain in the world above sea level?',
        ['Everest', 'K2', 'Kilimanjaro', 'Mont Blanc']],
      es: ['¿Cuál es la montaña más alta del mundo sobre el nivel del mar?',
        ['Everest', 'K2', 'Kilimanjaro', 'Mont Blanc']] },
    { id: 'mundo-006', nivel: 1, certa: 1,
      pt: ['Qual país é conhecido por ter o formato de uma bota no mapa?',
        ['Grécia', 'Itália', 'Portugal', 'Espanha']],
      en: ['Which country is known for having a boot shape on the map?',
        ['Greece', 'Italy', 'Portugal', 'Spain']],
      es: ['¿Qué país es conocido por tener forma de bota en el mapa?',
        ['Grecia', 'Italia', 'Portugal', 'España']] },
    { id: 'mundo-007', nivel: 1, certa: 2,
      pt: ['Qual é a moeda oficial do Japão?',
        ['Won', 'Yuan', 'Iene', 'Rupia']],
      en: ['What is the official currency of Japan?',
        ['Won', 'Yuan', 'Yen', 'Rupee']],
      es: ['¿Cuál es la moneda oficial de Japón?',
        ['Won', 'Yuan', 'Yen', 'Rupia']] },
    { id: 'mundo-008', nivel: 1, certa: 3,
      pt: ['Qual é a capital da Austrália?',
        ['Sydney', 'Melbourne', 'Brisbane', 'Camberra']],
      en: ['What is the capital of Australia?',
        ['Sydney', 'Melbourne', 'Brisbane', 'Canberra']],
      es: ['¿Cuál es la capital de Australia?',
        ['Sídney', 'Melbourne', 'Brisbane', 'Canberra']] },
    { id: 'mundo-009', nivel: 1, certa: 0,
      pt: ['Qual é o maior país do mundo em área?',
        ['Rússia', 'Canadá', 'China', 'Estados Unidos']],
      en: ['What is the largest country in the world by area?',
        ['Russia', 'Canada', 'China', 'United States']],
      es: ['¿Cuál es el país más grande del mundo por superficie?',
        ['Rusia', 'Canadá', 'China', 'Estados Unidos']] },
    { id: 'mundo-010', nivel: 1, certa: 1,
      pt: ['Qual é o menor país do mundo em área?',
        ['Mônaco', 'Cidade do Vaticano', 'San Marino', 'Liechtenstein']],
      en: ['What is the smallest country in the world by area?',
        ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein']],
      es: ['¿Cuál es el país más pequeño del mundo por superficie?',
        ['Mónaco', 'Ciudad del Vaticano', 'San Marino', 'Liechtenstein']] },
    { id: 'mundo-011', nivel: 1, certa: 2,
      pt: ['Qual é a capital do Canadá?',
        ['Toronto', 'Montreal', 'Ottawa', 'Vancouver']],
      en: ['What is the capital of Canada?',
        ['Toronto', 'Montreal', 'Ottawa', 'Vancouver']],
      es: ['¿Cuál es la capital de Canadá?',
        ['Toronto', 'Montreal', 'Ottawa', 'Vancouver']] },
    { id: 'mundo-012', nivel: 1, certa: 3,
      pt: ['A folha de bordo aparece na bandeira de qual país?',
        ['Austrália', 'Áustria', 'Nova Zelândia', 'Canadá']],
      en: ['The maple leaf appears on the flag of which country?',
        ['Australia', 'Austria', 'New Zealand', 'Canada']],
      es: ['¿La hoja de arce aparece en la bandera de qué país?',
        ['Australia', 'Austria', 'Nueva Zelanda', 'Canadá']] },
    { id: 'mundo-013', nivel: 1, certa: 0,
      pt: ['Em qual cidade fica o Cristo Redentor?',
        ['Rio de Janeiro', 'Lisboa', 'Buenos Aires', 'Cidade do México']],
      en: ['In which city is Christ the Redeemer located?',
        ['Rio de Janeiro', 'Lisbon', 'Buenos Aires', 'Mexico City']],
      es: ['¿En qué ciudad se encuentra el Cristo Redentor?',
        ['Río de Janeiro', 'Lisboa', 'Buenos Aires', 'Ciudad de México']] },
    { id: 'mundo-014', nivel: 1, certa: 1,
      pt: ['As pirâmides de Gizé ficam em qual país?',
        ['Sudão', 'Egito', 'Jordânia', 'Marrocos']],
      en: ['The Pyramids of Giza are in which country?',
        ['Sudan', 'Egypt', 'Jordan', 'Morocco']],
      es: ['¿Las pirámides de Guiza se encuentran en qué país?',
        ['Sudán', 'Egipto', 'Jordania', 'Marruecos']] },
    { id: 'mundo-015', nivel: 1, certa: 2,
      pt: ['Qual idioma é falado por mais pessoas no Brasil?',
        ['Espanhol', 'Inglês', 'Português', 'Italiano']],
      en: ['Which language is spoken by the most people in Brazil?',
        ['Spanish', 'English', 'Portuguese', 'Italian']],
      es: ['¿Qué idioma habla la mayor cantidad de personas en Brasil?',
        ['Español', 'Inglés', 'Portugués', 'Italiano']] },
    { id: 'mundo-016', nivel: 1, certa: 3,
      pt: ['Qual é a capital da Argentina?',
        ['Córdoba', 'Montevidéu', 'Santiago', 'Buenos Aires']],
      en: ['What is the capital of Argentina?',
        ['Córdoba', 'Montevideo', 'Santiago', 'Buenos Aires']],
      es: ['¿Cuál es la capital de Argentina?',
        ['Córdoba', 'Montevideo', 'Santiago', 'Buenos Aires']] },
    { id: 'mundo-017', nivel: 1, certa: 0,
      pt: ['Em qual continente fica o deserto do Saara?',
        ['África', 'Ásia', 'Europa', 'Oceania']],
      en: ['On which continent is the Sahara Desert located?',
        ['Africa', 'Asia', 'Europe', 'Oceania']],
      es: ['¿En qué continente se encuentra el desierto del Sáhara?',
        ['África', 'Asia', 'Europa', 'Oceanía']] },
    { id: 'mundo-018', nivel: 1, certa: 1,
      pt: ['Qual é a moeda oficial do Reino Unido?',
        ['Euro', 'Libra esterlina', 'Dólar', 'Franco suíço']],
      en: ['What is the official currency of the United Kingdom?',
        ['Euro', 'Pound sterling', 'Dollar', 'Swiss franc']],
      es: ['¿Cuál es la moneda oficial del Reino Unido?',
        ['Euro', 'Libra esterlina', 'Dólar', 'Franco suizo']] },
    { id: 'mundo-019', nivel: 1, certa: 2,
      pt: ['Em qual país fica a Grande Muralha?',
        ['Mongólia', 'Coreia do Sul', 'China', 'Índia']],
      en: ['In which country is the Great Wall located?',
        ['Mongolia', 'South Korea', 'China', 'India']],
      es: ['¿En qué país se encuentra la Gran Muralla?',
        ['Mongolia', 'Corea del Sur', 'China', 'India']] },
    { id: 'mundo-020', nivel: 1, certa: 3,
      pt: ['Em qual continente fica o Quênia?',
        ['Ásia', 'Europa', 'América do Sul', 'África']],
      en: ['On which continent is Kenya located?',
        ['Asia', 'Europe', 'South America', 'Africa']],
      es: ['¿En qué continente se encuentra Kenia?',
        ['Asia', 'Europa', 'América del Sur', 'África']] },
    { id: 'mundo-021', nivel: 2, certa: 0,
      pt: ['Por qual capital europeia o rio Danúbio passa?',
        ['Budapeste', 'Praga', 'Varsóvia', 'Madri']],
      en: ['Which European capital does the Danube flow through?',
        ['Budapest', 'Prague', 'Warsaw', 'Madrid']],
      es: ['¿Por qué capital europea pasa el río Danubio?',
        ['Budapest', 'Praga', 'Varsovia', 'Madrid']] },
    { id: 'mundo-022', nivel: 2, certa: 1,
      pt: ['Em qual continente fica a cordilheira dos Andes?',
        ['África', 'América do Sul', 'Ásia', 'Europa']],
      en: ['On which continent are the Andes located?',
        ['Africa', 'South America', 'Asia', 'Europe']],
      es: ['¿En qué continente se encuentra la cordillera de los Andes?',
        ['África', 'América del Sur', 'Asia', 'Europa']] },
    { id: 'mundo-023', nivel: 2, certa: 2,
      pt: ['Qual é a capital da Turquia?',
        ['Istambul', 'Esmirna', 'Ancara', 'Antália']],
      en: ['What is the capital of Turkey?',
        ['Istanbul', 'Izmir', 'Ankara', 'Antalya']],
      es: ['¿Cuál es la capital de Turquía?',
        ['Estambul', 'Esmirna', 'Ankara', 'Antalya']] },
    { id: 'mundo-024', nivel: 2, certa: 3,
      pt: ['A bandeira de qual país tem um círculo vermelho sobre fundo branco?',
        ['Bangladesh', 'Indonésia', 'Polônia', 'Japão']],
      en: ['Which country has a flag with a red circle on a white background?',
        ['Bangladesh', 'Indonesia', 'Poland', 'Japan']],
      es: ['¿La bandera de qué país tiene un círculo rojo sobre fondo blanco?',
        ['Bangladés', 'Indonesia', 'Polonia', 'Japón']] },
    { id: 'mundo-025', nivel: 2, certa: 0,
      pt: ['Em qual mar o rio Reno deságua?',
        ['Mar do Norte', 'Mar Báltico', 'Mar Negro', 'Mar Adriático']],
      en: ['Into which sea does the Rhine empty?',
        ['North Sea', 'Baltic Sea', 'Black Sea', 'Adriatic Sea']],
      es: ['¿En qué mar desemboca el río Rin?',
        ['Mar del Norte', 'Mar Báltico', 'Mar Negro', 'Mar Adriático']] },
    { id: 'mundo-026', nivel: 2, certa: 1,
      pt: ['Qual é a capital de Botsuana?',
        ['Francistown', 'Gaborone', 'Maun', 'Lobatse']],
      en: ['What is the capital of Botswana?',
        ['Francistown', 'Gaborone', 'Maun', 'Lobatse']],
      es: ['¿Cuál es la capital de Botsuana?',
        ['Francistown', 'Gaborone', 'Maun', 'Lobatse']] },
    { id: 'mundo-027', nivel: 2, certa: 2,
      pt: ['Em qual cidade fica a Torre de Pisa?',
        ['Florença', 'Roma', 'Pisa', 'Veneza']],
      en: ['In which city is the Leaning Tower of Pisa located?',
        ['Florence', 'Rome', 'Pisa', 'Venice']],
      es: ['¿En qué ciudad se encuentra la Torre de Pisa?',
        ['Florencia', 'Roma', 'Pisa', 'Venecia']] },
    { id: 'mundo-028', nivel: 2, certa: 3,
      pt: ['Quais dois países fazem fronteira com o lago Titicaca?',
        ['Chile e Peru', 'Bolívia e Chile', 'Equador e Peru', 'Bolívia e Peru']],
      en: ['Which two countries border Lake Titicaca?',
        ['Chile and Peru', 'Bolivia and Chile', 'Ecuador and Peru', 'Bolivia and Peru']],
      es: ['¿Qué dos países limitan con el lago Titicaca?',
        ['Chile y Perú', 'Bolivia y Chile', 'Ecuador y Perú', 'Bolivia y Perú']] },
    { id: 'mundo-029', nivel: 2, certa: 0,
      pt: ['Qual idioma é oficial na Áustria?',
        ['Alemão', 'Húngaro', 'Eslovaco', 'Esloveno']],
      en: ['Which language is official in Austria?',
        ['German', 'Hungarian', 'Slovak', 'Slovenian']],
      es: ['¿Qué idioma es oficial en Austria?',
        ['Alemán', 'Húngaro', 'Eslovaco', 'Esloveno']] },
    { id: 'mundo-030', nivel: 2, certa: 1,
      pt: ['Qual é a maior ilha do mundo?',
        ['Nova Guiné', 'Groenlândia', 'Bornéu', 'Madagascar']],
      en: ['What is the largest island in the world?',
        ['New Guinea', 'Greenland', 'Borneo', 'Madagascar']],
      es: ['¿Cuál es la isla más grande del mundo?',
        ['Nueva Guinea', 'Groenlandia', 'Borneo', 'Madagascar']] },
    { id: 'mundo-031', nivel: 2, certa: 2,
      pt: ['Qual é a capital do Marrocos?',
        ['Casablanca', 'Marrakech', 'Rabat', 'Fez']],
      en: ['What is the capital of Morocco?',
        ['Casablanca', 'Marrakesh', 'Rabat', 'Fez']],
      es: ['¿Cuál es la capital de Marruecos?',
        ['Casablanca', 'Marrakech', 'Rabat', 'Fez']] },
    { id: 'mundo-032', nivel: 2, certa: 3,
      pt: ['Quais dois países dividem as Cataratas Vitória?',
        ['Quênia e Tanzânia', 'Uganda e Ruanda', 'Maláui e Moçambique', 'Zâmbia e Zimbábue']],
      en: ['Which two countries share Victoria Falls?',
        ['Kenya and Tanzania', 'Uganda and Rwanda', 'Malawi and Mozambique', 'Zambia and Zimbabwe']],
      es: ['¿Qué dos países comparten las cataratas Victoria?',
        ['Kenia y Tanzania', 'Uganda y Ruanda', 'Malaui y Mozambique', 'Zambia y Zimbabue']] },
    { id: 'mundo-033', nivel: 2, certa: 0,
      pt: ['Qual é a moeda oficial da Suíça?',
        ['Franco suíço', 'Euro', 'Coroa sueca', 'Libra esterlina']],
      en: ['What is the official currency of Switzerland?',
        ['Swiss franc', 'Euro', 'Swedish krona', 'Pound sterling']],
      es: ['¿Cuál es la moneda oficial de Suiza?',
        ['Franco suizo', 'Euro', 'Corona sueca', 'Libra esterlina']] },
    { id: 'mundo-034', nivel: 2, certa: 1,
      pt: ['Quais continentes são atravessados pela linha do Equador?',
        ['África e Europa', 'África e América do Sul', 'Ásia e Europa', 'América do Norte e Oceania']],
      en: ['Which continents are crossed by the Equator?',
        ['Africa and Europe', 'Africa and South America', 'Asia and Europe', 'North America and Oceania']],
      es: ['¿Qué continentes son atravesados por el ecuador?',
        ['África y Europa', 'África y América del Sur', 'Asia y Europa', 'América del Norte y Oceanía']] },
    { id: 'mundo-035', nivel: 2, certa: 2,
      pt: ['Qual é a capital da Nova Zelândia?',
        ['Auckland', 'Christchurch', 'Wellington', 'Hamilton']],
      en: ['What is the capital of New Zealand?',
        ['Auckland', 'Christchurch', 'Wellington', 'Hamilton']],
      es: ['¿Cuál es la capital de Nueva Zelanda?',
        ['Auckland', 'Christchurch', 'Wellington', 'Hamilton']] },
    { id: 'mundo-036', nivel: 2, certa: 3,
      pt: ['O cedro é o símbolo presente na bandeira de qual país?',
        ['Síria', 'Jordânia', 'Chipre', 'Líbano']],
      en: ['The cedar is the symbol on the flag of which country?',
        ['Syria', 'Jordan', 'Cyprus', 'Lebanon']],
      es: ['¿El cedro es el símbolo presente en la bandera de qué país?',
        ['Siria', 'Jordania', 'Chipre', 'Líbano']] },
    { id: 'mundo-037', nivel: 2, certa: 0,
      pt: ['Qual rio atravessa Paris?',
        ['Sena', 'Tâmisa', 'Loire', 'Ródano']],
      en: ['Which river flows through Paris?',
        ['Seine', 'Thames', 'Loire', 'Rhône']],
      es: ['¿Qué río atraviesa París?',
        ['Sena', 'Támesis', 'Loira', 'Ródano']] },
    { id: 'mundo-038', nivel: 2, certa: 1,
      pt: ['Em qual país fica o monte Kilimanjaro?',
        ['Quênia', 'Tanzânia', 'Uganda', 'Etiópia']],
      en: ['In which country is Mount Kilimanjaro located?',
        ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia']],
      es: ['¿En qué país se encuentra el monte Kilimanjaro?',
        ['Kenia', 'Tanzania', 'Uganda', 'Etiopía']] },
    { id: 'mundo-039', nivel: 2, certa: 2,
      pt: ['Em qual país fica o lago Baikal?',
        ['Cazaquistão', 'Mongólia', 'Rússia', 'Finlândia']],
      en: ['In which country is Lake Baikal located?',
        ['Kazakhstan', 'Mongolia', 'Russia', 'Finland']],
      es: ['¿En qué país se encuentra el lago Baikal?',
        ['Kazajistán', 'Mongolia', 'Rusia', 'Finlandia']] },
    { id: 'mundo-040', nivel: 2, certa: 3,
      pt: ['Qual é a capital do Cazaquistão?',
        ['Almaty', 'Shymkent', 'Karaganda', 'Astana']],
      en: ['What is the capital of Kazakhstan?',
        ['Almaty', 'Shymkent', 'Karaganda', 'Astana']],
      es: ['¿Cuál es la capital de Kazajistán?',
        ['Almaty', 'Shymkent', 'Karagandá', 'Astaná']] },
    { id: 'mundo-041', nivel: 2, certa: 0,
      pt: ['Quais mares são ligados pelo Canal de Suez?',
        ['Mediterrâneo e Vermelho', 'Negro e Egeu', 'Báltico e do Norte', 'Arábico e Cáspio']],
      en: ['Which seas are connected by the Suez Canal?',
        ['Mediterranean and Red', 'Black and Aegean', 'Baltic and North', 'Arabian and Caspian']],
      es: ['¿Qué mares están conectados por el canal de Suez?',
        ['Mediterráneo y Rojo', 'Negro y Egeo', 'Báltico y del Norte', 'Arábigo y Caspio']] },
    { id: 'mundo-042', nivel: 2, certa: 1,
      pt: ['Qual é a moeda oficial da Coreia do Sul?',
        ['Iene', 'Won', 'Yuan', 'Baht']],
      en: ['What is the official currency of South Korea?',
        ['Yen', 'Won', 'Yuan', 'Baht']],
      es: ['¿Cuál es la moneda oficial de Corea del Sur?',
        ['Yen', 'Won', 'Yuan', 'Baht']] },
    { id: 'mundo-043', nivel: 2, certa: 2,
      pt: ['Quais países formam a maior parte da península Ibérica?',
        ['França e Espanha', 'Portugal e França', 'Portugal e Espanha', 'Espanha e Itália']],
      en: ['Which countries make up most of the Iberian Peninsula?',
        ['France and Spain', 'Portugal and France', 'Portugal and Spain', 'Spain and Italy']],
      es: ['¿Qué países forman la mayor parte de la península ibérica?',
        ['Francia y España', 'Portugal y Francia', 'Portugal y España', 'España e Italia']] },
    { id: 'mundo-044', nivel: 2, certa: 3,
      pt: ['Qual é a capital da Mongólia?',
        ['Erdenet', 'Darkhan', 'Choibalsan', 'Ulaanbaatar']],
      en: ['What is the capital of Mongolia?',
        ['Erdenet', 'Darkhan', 'Choibalsan', 'Ulaanbaatar']],
      es: ['¿Cuál es la capital de Mongolia?',
        ['Erdenet', 'Darkhan', 'Choibalsan', 'Ulán Bator']] },
    { id: 'mundo-045', nivel: 2, certa: 0,
      pt: ['Qual estreito separa as partes europeia e asiática de Istambul?',
        ['Bósforo', 'Gibraltar', 'Bering', 'Malaca']],
      en: ['Which strait separates the European and Asian parts of Istanbul?',
        ['Bosporus', 'Gibraltar', 'Bering', 'Malacca']],
      es: ['¿Qué estrecho separa las partes europea y asiática de Estambul?',
        ['Bósforo', 'Gibraltar', 'Bering', 'Malaca']] },
    { id: 'mundo-046', nivel: 3, certa: 1,
      pt: ['Qual país é completamente cercado pela África do Sul?',
        ['Essuatíni', 'Lesoto', 'Botsuana', 'Namíbia']],
      en: ['Which country is completely surrounded by South Africa?',
        ['Eswatini', 'Lesotho', 'Botswana', 'Namibia']],
      es: ['¿Qué país está completamente rodeado por Sudáfrica?',
        ['Esuatini', 'Lesoto', 'Botsuana', 'Namibia']] },
    { id: 'mundo-047', nivel: 3, certa: 2,
      pt: ['Qual é a capital de Mianmar?',
        ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagan']],
      en: ['What is the capital of Myanmar?',
        ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagan']],
      es: ['¿Cuál es la capital de Myanmar?',
        ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagán']] },
    { id: 'mundo-048', nivel: 3, certa: 3,
      pt: ['Qual é a capital de Burkina Faso?',
        ['Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Uagadugu']],
      en: ['What is the capital of Burkina Faso?',
        ['Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouagadougou']],
      es: ['¿Cuál es la capital de Burkina Faso?',
        ['Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Uagadugú']] },
    { id: 'mundo-049', nivel: 3, certa: 0,
      pt: ['A bandeira de qual país é a única do mundo que não é quadrilateral?',
        ['Nepal', 'Butão', 'Suíça', 'Japão']],
      en: ['Which country has the only non-quadrilateral national flag in the world?',
        ['Nepal', 'Bhutan', 'Switzerland', 'Japan']],
      es: ['¿La bandera de qué país es la única del mundo que no es cuadrilateral?',
        ['Nepal', 'Bután', 'Suiza', 'Japón']] },
    { id: 'mundo-050', nivel: 3, certa: 1,
      pt: ['Qual é a capital da Namíbia?',
        ['Swakopmund', 'Windhoek', 'Rundu', 'Walvis Bay']],
      en: ['What is the capital of Namibia?',
        ['Swakopmund', 'Windhoek', 'Rundu', 'Walvis Bay']],
      es: ['¿Cuál es la capital de Namibia?',
        ['Swakopmund', 'Windhoek', 'Rundu', 'Walvis Bay']] },
    { id: 'mundo-051', nivel: 3, certa: 2,
      pt: ['Qual é a capital legislativa do Sri Lanka?',
        ['Colombo', 'Kandy', 'Sri Jayawardenepura Kotte', 'Galle']],
      en: ['What is the legislative capital of Sri Lanka?',
        ['Colombo', 'Kandy', 'Sri Jayawardenepura Kotte', 'Galle']],
      es: ['¿Cuál es la capital legislativa de Sri Lanka?',
        ['Colombo', 'Kandy', 'Sri Jayawardenepura Kotte', 'Galle']] },
    { id: 'mundo-052', nivel: 3, certa: 3,
      pt: ['Qual é a capital do Suriname?',
        ['Nieuw Nickerie', 'Albina', 'Moengo', 'Paramaribo']],
      en: ['What is the capital of Suriname?',
        ['Nieuw Nickerie', 'Albina', 'Moengo', 'Paramaribo']],
      es: ['¿Cuál es la capital de Surinam?',
        ['Nieuw Nickerie', 'Albina', 'Moengo', 'Paramaribo']] },
    { id: 'mundo-053', nivel: 3, certa: 0,
      pt: ['Qual é a capital do Quirguistão?',
        ['Bisqueque', 'Osh', 'Karakol', 'Jalal-Abad']],
      en: ['What is the capital of Kyrgyzstan?',
        ['Bishkek', 'Osh', 'Karakol', 'Jalal-Abad']],
      es: ['¿Cuál es la capital de Kirguistán?',
        ['Biskek', 'Osh', 'Karakol', 'Jalal-Abad']] },
    { id: 'mundo-054', nivel: 3, certa: 1,
      pt: ['Qual mar fica entre a península Arábica e o nordeste da África?',
        ['Mar Arábico', 'Mar Vermelho', 'Mar Negro', 'Mar Cáspio']],
      en: ['Which sea lies between the Arabian Peninsula and northeastern Africa?',
        ['Arabian Sea', 'Red Sea', 'Black Sea', 'Caspian Sea']],
      es: ['¿Qué mar se encuentra entre la península arábiga y el noreste de África?',
        ['Mar Arábigo', 'Mar Rojo', 'Mar Negro', 'Mar Caspio']] },
    { id: 'mundo-055', nivel: 3, certa: 2,
      pt: ['Qual é a capital do Butão?',
        ['Paro', 'Punakha', 'Thimphu', 'Trongsa']],
      en: ['What is the capital of Bhutan?',
        ['Paro', 'Punakha', 'Thimphu', 'Trongsa']],
      es: ['¿Cuál es la capital de Bután?',
        ['Paro', 'Punakha', 'Timbu', 'Trongsa']] },
    { id: 'mundo-056', nivel: 3, certa: 3,
      pt: ['Qual país tem neerlandês, francês e alemão como idiomas oficiais?',
        ['Luxemburgo', 'Suíça', 'Áustria', 'Bélgica']],
      en: ['Which country has Dutch, French, and German as official languages?',
        ['Luxembourg', 'Switzerland', 'Austria', 'Belgium']],
      es: ['¿Qué país tiene neerlandés, francés y alemán como idiomas oficiales?',
        ['Luxemburgo', 'Suiza', 'Austria', 'Bélgica']] },
    { id: 'mundo-057', nivel: 3, certa: 0,
      pt: ['Qual é a capital de Madagascar?',
        ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga']],
      en: ['What is the capital of Madagascar?',
        ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga']],
      es: ['¿Cuál es la capital de Madagascar?',
        ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga']] },
    { id: 'mundo-058', nivel: 3, certa: 1,
      pt: ['Qual é o rio mais longo da Europa?',
        ['Danúbio', 'Volga', 'Dniepre', 'Elba']],
      en: ['What is the longest river in Europe?',
        ['Danube', 'Volga', 'Dnieper', 'Elbe']],
      es: ['¿Cuál es el río más largo de Europa?',
        ['Danubio', 'Volga', 'Dniéper', 'Elba']] },
    { id: 'mundo-059', nivel: 3, certa: 2,
      pt: ['Qual é a capital do Laos?',
        ['Luang Prabang', 'Pakse', 'Vientiane', 'Savannakhet']],
      en: ['What is the capital of Laos?',
        ['Luang Prabang', 'Pakse', 'Vientiane', 'Savannakhet']],
      es: ['¿Cuál es la capital de Laos?',
        ['Luang Prabang', 'Pakse', 'Vientián', 'Savannakhet']] },
    { id: 'mundo-060', nivel: 3, certa: 3,
      pt: ['Qual estreito separa o Alasca da Rússia?',
        ['Gibraltar', 'Bósforo', 'Malaca', 'Bering']],
      en: ['Which strait separates Alaska from Russia?',
        ['Gibraltar', 'Bosporus', 'Malacca', 'Bering']],
      es: ['¿Qué estrecho separa Alaska de Rusia?',
        ['Gibraltar', 'Bósforo', 'Malaca', 'Bering']] },
  ];
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.mundo = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
