'use strict';

/* Quiz -- tema "musica". Cada pergunta: id estavel, nivel (1 facil, 2 medio,
 * 3 dificil; nao aparece na tela), indice da certa (vale nas tres linguas)
 * e o texto por lingua. Criterios na spec 2026-10-03-idiomas, secao 5.1. */

(function (root) {
  let numero = 0;
  function lancou(nivel, certa, titulo, alternativas) {
    numero += 1;
    const id = `musica-${String(numero).padStart(3, '0')}`;
    return { id, nivel, certa,
      pt: [`Qual artista ou grupo lançou "${titulo}"?`, alternativas],
      en: [`Which artist or group released "${titulo}"?`, alternativas],
      es: [`¿Qué artista o grupo lanzó "${titulo}"?`, alternativas] };
  }

  /* Pergunta livre (instrumento, genero, autoria): textos por lingua. */
  function livre(nivel, certa, pt, en, es) {
    numero += 1;
    const id = `musica-${String(numero).padStart(3, '0')}`;
    return { id, nivel, certa, pt, en, es };
  }

  const perguntas = [
    lancou(1, 0, 'Hey Jude', ['The Beatles', 'The Rolling Stones', 'The Kinks', 'The Who']),
    lancou(1, 1, 'Billie Jean', ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Bruno Mars']),
    lancou(1, 2, 'Hips Don\'t Lie', ['Jennifer Lopez', 'Beyoncé', 'Shakira', 'Rihanna']),
    lancou(1, 3, 'Bohemian Rhapsody', ['ABBA', 'U2', 'The Police', 'Queen']),
    livre(1, 0,
      ['Qual destes instrumentos é de sopro?', ['Flauta', 'Violino', 'Harpa', 'Violão']],
      ['Which of these is a wind instrument?', ['Flute', 'Violin', 'Harp', 'Guitar']],
      ['¿Cuál de estos instrumentos es de viento?', ['Flauta', 'Violín', 'Arpa', 'Guitarra']]),
    lancou(1, 1, 'Dancing Queen', ['Boney M.', 'ABBA', 'Bee Gees', 'A-ha']),
    lancou(1, 2, 'Firework', ['Pink', 'Taylor Swift', 'Katy Perry', 'Miley Cyrus']),
    lancou(1, 3, 'Smells Like Teen Spirit', ['Pearl Jam', 'Radiohead', 'Oasis', 'Nirvana']),
    livre(1, 0,
      ['Quem conduz uma orquestra durante a apresentação?',
        ['O maestro', 'O violinista', 'O pianista', 'O produtor']],
      ['Who conducts an orchestra during a performance?',
        ['The conductor', 'The violinist', 'The pianist', 'The producer']],
      ['¿Quién dirige una orquesta durante la actuación?',
        ['El director', 'El violinista', 'El pianista', 'El productor']]),
    livre(1, 1,
      ['Em qual país nasceu o flamenco?', ['Portugal', 'Espanha', 'México', 'Itália']],
      ['In which country did flamenco originate?', ['Portugal', 'Spain', 'Mexico', 'Italy']],
      ['¿En qué país nació el flamenco?', ['Portugal', 'España', 'México', 'Italia']]),
    lancou(1, 2, 'Blinding Lights', ['Drake', 'Bruno Mars', 'The Weeknd', 'Post Malone']),
    livre(1, 3,
      ['Qual destes gêneros musicais nasceu no Brasil?', ['Salsa', 'Reggae', 'Flamenco', 'Bossa nova']],
      ['Which of these music genres was born in Brazil?', ['Salsa', 'Reggae', 'Flamenco', 'Bossa nova']],
      ['¿Cuál de estos géneros musicales nació en Brasil?', ['Salsa', 'Reggae', 'Flamenco', 'Bossa nova']]),
    lancou(1, 0, 'Havana', ['Camila Cabello', 'Selena Gomez', 'Demi Lovato', 'Rosalía']),
    livre(1, 1,
      ['O K-pop é o pop de qual país?', ['Japão', 'Coreia do Sul', 'China', 'Tailândia']],
      ['K-pop is the pop music of which country?', ['Japan', 'South Korea', 'China', 'Thailand']],
      ['¿De qué país es el K-pop?', ['Japón', 'Corea del Sur', 'China', 'Tailandia']]),
    livre(1, 2,
      ['Qual destes instrumentos é de percussão?', ['Violino', 'Trombone', 'Bateria', 'Harpa']],
      ['Which of these is a percussion instrument?', ['Violin', 'Trombone', 'Drums', 'Harp']],
      ['¿Cuál de estos instrumentos es de percusión?', ['Violín', 'Trombón', 'Batería', 'Arpa']]),
    lancou(1, 3, 'Despacito', ['J Balvin', 'Bad Bunny', 'Maluma', 'Luis Fonsi']),
    livre(1, 0,
      ['Qual destes instrumentos é tocado com um arco?', ['Violino', 'Flauta', 'Trompete', 'Piano']],
      ['Which of these instruments is played with a bow?', ['Violin', 'Flute', 'Trumpet', 'Piano']],
      ['¿Cuál de estos instrumentos se toca con arco?', ['Violín', 'Flauta', 'Trompeta', 'Piano']]),
    lancou(1, 1, 'Bad Guy', ['Lorde', 'Billie Eilish', 'Olivia Rodrigo', 'Halsey']),
    lancou(1, 2, 'Wonderwall', ['Blur', 'Pulp', 'Oasis', 'Suede']),
    lancou(1, 3, 'Girls Just Want to Have Fun', ['Tina Turner', 'Belinda Carlisle', 'Pat Benatar', 'Cyndi Lauper']),
    lancou(2, 0, 'The Dark Side of the Moon', ['Pink Floyd', 'Genesis', 'Yes', 'Led Zeppelin']),
    lancou(2, 1, 'Tití Me Preguntó', ['Daddy Yankee', 'Bad Bunny', 'J Balvin', 'Ozuna']),
    livre(2, 2,
      ['Qual músico nigeriano é considerado o criador do afrobeat?',
        ['Youssou N\'Dour', 'Burna Boy', 'Fela Kuti', 'Femi Kuti']],
      ['Which Nigerian musician is considered the creator of afrobeat?',
        ['Youssou N\'Dour', 'Burna Boy', 'Fela Kuti', 'Femi Kuti']],
      ['¿Qué músico nigeriano es considerado el creador del afrobeat?',
        ['Youssou N\'Dour', 'Burna Boy', 'Fela Kuti', 'Femi Kuti']]),
    livre(2, 3,
      ['Quem compôs a música de "Garota de Ipanema"?',
        ['João Gilberto', 'Chico Buarque', 'Caetano Veloso', 'Tom Jobim']],
      ['Who composed the music of "Garota de Ipanema"?',
        ['João Gilberto', 'Chico Buarque', 'Caetano Veloso', 'Tom Jobim']],
      ['¿Quién compuso la música de "Garota de Ipanema"?',
        ['João Gilberto', 'Chico Buarque', 'Caetano Veloso', 'Tom Jobim']]),
    livre(2, 0,
      ['Qual destes gêneros musicais nasceu na Jamaica?', ['Reggae', 'Flamenco', 'Tango', 'Jazz']],
      ['Which of these music genres was born in Jamaica?', ['Reggae', 'Flamenco', 'Tango', 'Jazz']],
      ['¿Cuál de estos géneros musicales nació en Jamaica?', ['Reggae', 'Flamenco', 'Tango', 'Jazz']]),
    lancou(2, 1, 'Random Access Memories', ['Justice', 'Daft Punk', 'Air', 'Cassius']),
    livre(2, 2,
      ['Qual show beneficente de 1985 foi transmitido ao mundo de Londres e da Filadélfia no mesmo dia?',
        ['Live 8', 'Concert for Bangladesh', 'Live Aid', 'Farm Aid']],
      ['Which 1985 charity concert was broadcast worldwide from London and Philadelphia on the same day?',
        ['Live 8', 'Concert for Bangladesh', 'Live Aid', 'Farm Aid']],
      ['¿Qué concierto benéfico de 1985 se transmitió al mundo desde Londres y Filadelfia el mismo día?',
        ['Live 8', 'Concert for Bangladesh', 'Live Aid', 'Farm Aid']]),
    livre(2, 3,
      ['Qual destes instrumentos faz parte da família das cordas?', ['Flauta', 'Trompete', 'Clarinete', 'Violoncelo']],
      ['Which of these instruments belongs to the string family?', ['Flute', 'Trumpet', 'Clarinet', 'Cello']],
      ['¿Cuál de estos instrumentos pertenece a la familia de las cuerdas?',
        ['Flauta', 'Trompeta', 'Clarinete', 'Violonchelo']]),
    lancou(2, 0, 'Dynamite', ['BTS', 'EXO', 'Blackpink', 'Seventeen']),
    lancou(2, 1, 'How You Like That', ['TWICE', 'Blackpink', 'Red Velvet', 'NewJeans']),
    lancou(2, 2, 'Take On Me', ['Duran Duran', 'Depeche Mode', 'A-ha', 'Erasure']),
    lancou(2, 3, 'Sweet Dreams (Are Made of This)', ['The Human League', 'Soft Cell', 'Depeche Mode', 'Eurythmics']),
    livre(2, 0,
      ['Qual país é a origem do J-pop?', ['Japão', 'Coreia do Sul', 'Tailândia', 'Taiwan']],
      ['Which country is the origin of J-pop?', ['Japan', 'South Korea', 'Thailand', 'Taiwan']],
      ['¿Cuál es el país de origen del J-pop?', ['Japón', 'Corea del Sur', 'Tailandia', 'Taiwán']]),
    lancou(2, 1, 'The Miseducation of Lauryn Hill', ['Erykah Badu', 'Lauryn Hill', 'Mary J. Blige', 'Missy Elliott']),
    livre(2, 2,
      ['Quem compôs "As Quatro Estações"?', ['Bach', 'Mozart', 'Vivaldi', 'Haydn']],
      ['Who composed "The Four Seasons"?', ['Bach', 'Mozart', 'Vivaldi', 'Haydn']],
      ['¿Quién compuso "Las cuatro estaciones"?', ['Bach', 'Mozart', 'Vivaldi', 'Haydn']]),
    livre(2, 3,
      ['Qual festival de 1969, no estado de Nova York, teve Jimi Hendrix, Janis Joplin e The Who?',
        ['Glastonbury', 'Monterey Pop', 'Coachella', 'Woodstock']],
      ['Which 1969 festival in New York State featured Jimi Hendrix, Janis Joplin and The Who?',
        ['Glastonbury', 'Monterey Pop', 'Coachella', 'Woodstock']],
      ['¿Qué festival de 1969, en el estado de Nueva York, tuvo a Jimi Hendrix, Janis Joplin y The Who?',
        ['Glastonbury', 'Monterey Pop', 'Coachella', 'Woodstock']]),
    lancou(2, 0, 'Feel Good Inc.', ['Gorillaz', 'Blur', 'Oasis', 'Radiohead']),
    livre(2, 1,
      ['Quem compôs "I Will Always Love You", sucesso de Whitney Houston?',
        ['Whitney Houston', 'Dolly Parton', 'Linda Ronstadt', 'Barbra Streisand']],
      ['Who wrote "I Will Always Love You", a hit for Whitney Houston?',
        ['Whitney Houston', 'Dolly Parton', 'Linda Ronstadt', 'Barbra Streisand']],
      ['¿Quién escribió "I Will Always Love You", éxito de Whitney Houston?',
        ['Whitney Houston', 'Dolly Parton', 'Linda Ronstadt', 'Barbra Streisand']]),
    lancou(2, 2, 'No Woman, No Cry', [
      'Peter Tosh', 'Jimmy Cliff', 'Bob Marley & The Wailers', 'Toots and the Maytals']),
    lancou(2, 3, 'Kashmir', ['Deep Purple', 'Black Sabbath', 'The Who', 'Led Zeppelin']),
    livre(2, 0,
      ['Quem compôs a Nona Sinfonia, que termina com o "Hino à Alegria"?',
        ['Beethoven', 'Mozart', 'Bach', 'Chopin']],
      ['Who composed the Ninth Symphony, which ends with the "Ode to Joy"?',
        ['Beethoven', 'Mozart', 'Bach', 'Chopin']],
      ['¿Quién compuso la Novena Sinfonía, que termina con la "Oda a la alegría"?',
        ['Beethoven', 'Mozart', 'Bach', 'Chopin']]),
    lancou(2, 1, 'Halo', ['Rihanna', 'Beyoncé', 'Alicia Keys', 'Leona Lewis']),
    lancou(2, 2, 'Somebody That I Used to Know', ['Vance Joy', 'Hozier', 'Gotye', 'James Blake']),
    lancou(2, 3, 'La Tortura', ['Thalía', 'Paulina Rubio', 'Nelly Furtado', 'Shakira']),
    livre(2, 0,
      ['Quantas cordas tem um violão padrão?', ['Seis', 'Quatro', 'Cinco', 'Oito']],
      ['How many strings does a standard guitar have?', ['Six', 'Four', 'Five', 'Eight']],
      ['¿Cuántas cuerdas tiene una guitarra estándar?', ['Seis', 'Cuatro', 'Cinco', 'Ocho']]),
    livre(3, 1,
      ['Qual cantora cubana ficou conhecida como a "Rainha da Salsa"?',
        ['Gloria Estefan', 'Celia Cruz', 'Selena', 'Thalía']],
      ['Which Cuban singer became known as the "Queen of Salsa"?',
        ['Gloria Estefan', 'Celia Cruz', 'Selena', 'Thalía']],
      ['¿Qué cantante cubana fue conocida como la "Reina de la Salsa"?',
        ['Gloria Estefan', 'Celia Cruz', 'Selena', 'Thalía']]),
    lancou(3, 2, 'Homogenic', ['PJ Harvey', 'Fiona Apple', 'Björk', 'Tori Amos']),
    lancou(3, 3, 'Ágætis byrjun', ['Múm', 'Björk', 'Of Monsters and Men', 'Sigur Rós']),
    lancou(3, 0, 'Hejira', ['Joni Mitchell', 'Carole King', 'Joan Baez', 'Carly Simon']),
    lancou(3, 1, 'Vespertine', ['FKA twigs', 'Björk', 'Sophie', 'Grimes']),
    livre(3, 2,
      ['Qual instrumento era a marca do jazzista Miles Davis?', ['Saxofone', 'Piano', 'Trompete', 'Contrabaixo']],
      ['Which instrument was the trademark of jazz musician Miles Davis?',
        ['Saxophone', 'Piano', 'Trumpet', 'Double bass']],
      ['¿Qué instrumento era la marca del jazzista Miles Davis?', ['Saxofón', 'Piano', 'Trompeta', 'Contrabajo']]),
    lancou(3, 3, 'Dummy', ['Tricky', 'Massive Attack', 'Sneaker Pimps', 'Portishead']),
    lancou(3, 0, 'Since I Left You', ['The Avalanches', 'The Chemical Brothers', 'Air', 'M83']),
    lancou(3, 1, 'In Rainbows', ['Muse', 'Radiohead', 'Coldplay', 'Interpol']),
    lancou(3, 2, 'The Suburbs', ['The National', 'The Strokes', 'Arcade Fire', 'Interpol']),
    lancou(3, 3, 'Blue Lines', ['Soul II Soul', 'Portishead', 'Tricky', 'Massive Attack']),
    lancou(3, 0, 'Aquemini', ['Outkast', 'The Roots', 'De La Soul', 'A Tribe Called Quest']),
    lancou(3, 1, 'Illinois', ['Sufjan Stevens', 'Bon Iver', 'Fleet Foxes', 'Iron & Wine']),
    lancou(3, 2, 'The Low End Theory', ['De La Soul', 'Gang Starr', 'A Tribe Called Quest', 'The Roots']),
    lancou(3, 3, 'Discovery', ['Air', 'Justice', 'Cassius', 'Daft Punk']),
  ];
  root.GoLive = root.GoLive || {};
  root.GoLive.mesaQuizBanco = root.GoLive.mesaQuizBanco || {};
  root.GoLive.mesaQuizBanco.musica = perguntas;
  if (typeof module !== 'undefined') module.exports = perguntas;
})(globalThis);
