// Dados de busca do emoji; nao sao texto de tela.
'use strict';

(function (root) {
  const KEYWORDS = {
  "😀": "smile feliz alegre",
  "😃": "smile animado feliz",
  "😄": "smile rindo feliz",
  "😁": "smile dentes alegre",
  "😆": "risada gargalhada rindo",
  "😅": "risada nervoso suor alivio",
  "🤣": "rolando de rir gargalhada chao",
  "😂": "chorando de rir lagrima risada",
  "🙂": "smile leve simpatico",
  "🙃": "de cabeca para baixo ironia",
  "😉": "piscada flerte",
  "😊": "smile timido fofo",
  "😇": "anjo aureola inocente",
  "🥰": "apaixonado coracoes love",
  "😍": "heart love",
  "🤩": "estrelas uau incrivel",
  "😘": "beijo mandando",
  "😗": "beijo assobio",
  "😙": "beijo smile",
  "😋": "delicioso lingua gostoso",
  "😛": "lingua brincadeira",
  "😜": "lingua piscada zoeira",
  "🤪": "louco doido maluco",
  "🤨": "sobrancelha duvida desconfiado",
  "🧐": "monoculo analisando curioso",
  "🤓": "nerd oculos estudioso",
  "😎": "oculos de sun estiloso legal",
  "🥸": "disfarce bigode oculos",
  "🤯": "explodindo mente chocado",
  "😏": "malicioso sorrisinho",
  "😒": "sem graca entediado",
  "🙄": "revirando os olhos ironia",
  "😬": "careta constrangido",
  "😮‍💨": "suspiro alivio cansaco",
  "🤔": "pensando duvida",
  "🤫": "silencio segredo shh",
  "🤭": "ops risadinha vergonha",
  "😴": "dormindo sono cansado",
  "😪": "sono cansado",
  "🥱": "bocejo tedio sono",
  "😷": "mascara doente",
  "🤒": "febre doente termometro",
  "🤕": "machucado curativo",
  "🤢": "enjoado nojo",
  "🤮": "vomitando nojo passando mal",
  "🥵": "calor quente derretendo",
  "🥶": "frio congelando",
  "😵‍💫": "tonto confuso",
  "🤠": "cauboi chapeu",
  "🥳": "party comemorando aniversario",
  "😤": "bufando irritado determinado",
  "😡": "bravo raiva furioso",
  "🤬": "xingando palavrao raiva",
  "😞": "decepcionado triste",
  "😔": "pensativo triste",
  "😢": "chorando triste lagrima",
  "😭": "chorando muito desesperado",
  "😱": "grito susto medo",
  "😨": "medo assustado",
  "😰": "ansioso suor nervoso",
  "😥": "aliviado triste",
  "😓": "suor derrota cansado",
  "🥹": "emocionado segurando lagrima",
  "😳": "corado surpreso envergonhado",
  "🫠": "derretendo constrangido",
  "🥲": "smile com lagrima emocionado",
  "😶": "sem mouth calado",
  "😐": "neutro sem reacao",
  "😑": "inexpressivo sem paciencia",
  "🫡": "continencia salve respeito",
  "🤝": "aperto de hand acordo combinado",
  "💀": "caveira morri morto",
  "👻": "ghost assombracao",
  "👽": "alien et",
  "🤖": "robot bot",
  "💩": "coco merda ruim",
  "🤡": "clown",
  "😈": "diabo travesso",
  "🫶": "heart love",
  "👍": "joia positivo curti ok",
  "👎": "negativo nao ruim",
  "👌": "ok perfeito certo",
  "🤌": "italiano dedos gesto",
  "✌️": "paz vitoria dois",
  "🤞": "dedos cruzados sorte torcendo",
  "🤟": "te amo rock",
  "🤘": "rock chifres metal",
  "🤙": "me liga shaka",
  "👈": "aponta esquerda",
  "👉": "aponta direita",
  "👆": "aponta cima",
  "👇": "aponta baixo",
  "☝️": "atencao um dedo",
  "✋": "hand parada alto",
  "🖐️": "hand aberta dedos",
  "🖖": "vulcano spock",
  "👋": "tchau oi aceno",
  "🤚": "hand costas",
  "🙏": "obrigado por favor reza",
  "✍️": "escrevendo anotando",
  "👏": "palmas aplauso parabens",
  "🙌": "maos pro alto comemorando",
  "👐": "maos abertas abraco",
  "🤲": "maos juntas pedido",
  "💪": "forca biceps musculo",
  "🦾": "braco robotico forte",
  "🫵": "voce aponta",
  "👀": "olhos olhando vendo",
  "👁️": "eye vendo",
  "🧠": "cerebro ideia inteligente",
  "🫀": "heart love",
  "👶": "bebe crianca",
  "🧒": "crianca",
  "🧑": "pessoa",
  "👨": "homem",
  "👩": "mulher",
  "🧓": "idoso velho",
  "👮": "policia guarda",
  "🕵️": "detetive investigando",
  "👨‍💻": "programador dev computer",
  "👩‍💻": "programadora dev computer",
  "🧑‍🍳": "cozinheiro chef",
  "🦸": "heroi super",
  "🧙": "mago feiticeiro",
  "🧟": "zumbi",
  "🎅": "papai noel natal",
  "🕺": "dancando homem party",
  "💃": "dancando mulher party",
  "🏃": "correndo fugindo pressa",
  "🧘": "meditando calma yoga",
  "🤦": "facepalm nao acredito",
  "🤷": "sei la ombros duvida",
  "🙋": "levantando hand eu",
  "🙅": "nao pode proibido",
  "🙆": "ok certo",
  "🐶": "dog",
  "🐱": "cat",
  "🐭": "mouse",
  "🐹": "hamster",
  "🐰": "rabbit",
  "🦊": "raposa",
  "🐻": "bear",
  "🐼": "panda",
  "🐨": "coala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow boi",
  "🐷": "pig",
  "🐸": "sapo",
  "🐵": "monkey",
  "🙈": "monkey olhos nao vejo",
  "🐔": "galinha",
  "🐧": "pinguim",
  "🐦": "bird",
  "🦆": "pato",
  "🦅": "aguia",
  "🦉": "coruja",
  "🐺": "lobo",
  "🐗": "javali",
  "🐴": "cavalo",
  "🦄": "unicornio",
  "🐝": "abelha",
  "🐛": "lagarta bug",
  "🦋": "borboleta",
  "🐌": "lesma devagar",
  "🐞": "joaninha bug",
  "🐜": "formiga",
  "🕷️": "aranha",
  "🐢": "tartaruga lento",
  "🐍": "cobra",
  "🦎": "lagartixa",
  "🐙": "polvo",
  "🦑": "lula",
  "🦐": "camarao",
  "🐠": "fish tropical",
  "🐟": "fish",
  "🐬": "golfinho",
  "🐳": "baleia",
  "🦈": "tubarao",
  "🐊": "jacare crocodilo",
  "🐘": "elefante",
  "🦒": "girafa",
  "🦘": "canguru",
  "🐄": "cow",
  "🌵": "cacto deserto",
  "🌲": "pinheiro tree",
  "🌳": "tree",
  "🌴": "coqueiro palmeira praia",
  "🍀": "trevo sorte",
  "🍁": "folha outono",
  "🌺": "flower hibisco",
  "🌸": "flower cerejeira",
  "🌻": "girassol flower",
  "🌹": "rosa flower",
  "🌼": "margarida flower",
  "🌷": "tulipa flower",
  "🌞": "sun dia",
  "🌝": "moon cheia rosto",
  "🌙": "moon noite",
  "⭐": "star",
  "🌟": "star brilhante",
  "✨": "brilho magia faisca",
  "⚡": "lightning energia rapido",
  "🔥": "fire top incrivel",
  "💧": "gota water",
  "🌊": "onda mar",
  "🌈": "arco iris",
  "☀️": "sun ensolarado",
  "⛅": "nublado sun nuvem",
  "☁️": "nuvem nublado",
  "🌧️": "rain chovendo",
  "⛈️": "tempestade lightning rain",
  "❄️": "snow floco frio",
  "⛄": "boneco de snow",
  "🌪️": "tornado furacao",
  "🍏": "maca verde fruta",
  "🍎": "maca fruta",
  "🍐": "pera fruta",
  "🍊": "laranja fruta",
  "🍋": "limao fruta",
  "🍌": "banana fruta",
  "🍉": "melancia fruta",
  "🍇": "uva fruta",
  "🍓": "morango fruta",
  "🫐": "mirtilo fruta",
  "🍒": "cereja fruta",
  "🍑": "pessego bunda fruta",
  "🥭": "manga fruta",
  "🍍": "abacaxi fruta",
  "🥥": "coco fruta",
  "🥝": "kiwi fruta",
  "🍅": "tomate",
  "🥑": "abacate",
  "🌽": "milho",
  "🥕": "cenoura",
  "🥔": "batata",
  "🍞": "bread",
  "🥐": "croissant bread",
  "🥖": "baguete bread",
  "🧀": "cheese",
  "🥚": "ovo",
  "🍳": "ovo frito coffee da manha",
  "🥓": "bacon",
  "🍔": "hamburguer lanche",
  "🍟": "batata frita",
  "🍕": "pizza",
  "🌭": "dog quente hot",
  "🥪": "sanduiche lanche",
  "🌮": "taco",
  "🌯": "burrito wrap",
  "🥗": "salada",
  "🍝": "macarrao massa",
  "🍜": "lamen sopa macarrao",
  "🍲": "panela ensopado",
  "🍛": "curry arroz",
  "🍣": "sushi",
  "🍤": "camarao frito",
  "🍚": "arroz",
  "🍦": "sorvete casquinha",
  "🍩": "rosquinha donut",
  "🍪": "biscoito cookie",
  "🎂": "cake aniversario",
  "🍰": "fatia de cake",
  "🧁": "cupcake bolinho",
  "🍫": "chocolate",
  "🍬": "bala doce",
  "🍿": "pipoca filme",
  "🧂": "sal",
  "☕": "coffee",
  "🍵": "cha",
  "🧃": "suco caixinha",
  "🥤": "refrigerante copo",
  "🍺": "beer chopp",
  "🍻": "brinde beer saude",
  "🍷": "vinho taca",
  "🥂": "brinde champanhe comemorar",
  "🍾": "champanhe comemoracao",
  "🥃": "whisky dose",
  "🧉": "chimarrao mate",
  "🎮": "jogo videogame controle",
  "🕹️": "joystick arcade jogo",
  "🎲": "dado sorte jogo",
  "🃏": "coringa carta",
  "🎯": "alvo mira acerto",
  "🎰": "caca niquel sorte",
  "🧩": "quebra cabeca peca",
  "♟️": "xadrez peao",
  "⚽": "football bola",
  "🏀": "basketball bola",
  "🏈": "football americano",
  "⚾": "beisebol",
  "🎾": "tenis",
  "🏐": "volei",
  "🏓": "ping pong tenis de mesa",
  "🏸": "badminton",
  "🥅": "gol trave",
  "🏆": "trophy campeao vitoria",
  "🥇": "ouro primeiro medal",
  "🥈": "prata segundo medal",
  "🥉": "bronze terceiro medal",
  "🎖️": "medal honra",
  "🏅": "medal esporte",
  "🎽": "corrida camiseta",
  "🛹": "skate",
  "🚴": "bicicleta ciclismo",
  "🏋️": "academia musculacao peso",
  "🤺": "esgrima",
  "🥊": "boxe luva",
  "🎣": "pescaria vara",
  "🎸": "guitarra violao music",
  "🎹": "piano teclado music",
  "🥁": "bateria tambor music",
  "🎺": "trompete music",
  "🎤": "microfone cantar karaoke",
  "🎧": "fone de ouvido music",
  "🎬": "claquete filme cinema",
  "🎨": "arte pintura paleta",
  "🎭": "teatro mascaras",
  "🎪": "circo",
  "🎉": "party comemoracao parabens",
  "🎊": "confete party",
  "🎈": "balao party",
  "🎁": "gift",
  "🎃": "halloween abobora",
  "🎄": "natal tree",
  "🧨": "dinamite explosivo",
  "📸": "foto camera flash",
  "🚗": "car automovel",
  "🚕": "taxi",
  "🚙": "suv car",
  "🚌": "bus",
  "🏎️": "corrida formula car",
  "🚓": "viatura policia",
  "🚑": "ambulancia",
  "🚒": "bombeiro caminhao",
  "🚚": "caminhao entrega",
  "🚜": "trator",
  "🏍️": "moto",
  "🛵": "scooter moto",
  "🚲": "bicicleta bike",
  "✈️": "airplane voo viagem",
  "🚀": "rocket lancamento rapido",
  "🛸": "disco voador ovni",
  "🚁": "helicoptero",
  "⛵": "veleiro barco",
  "🚢": "ship",
  "🚂": "train locomotiva",
  "🚇": "metro",
  "🗺️": "mapa",
  "🧭": "bussola direcao",
  "🏔️": "montanha snow",
  "🌋": "vulcao",
  "🏝️": "ilha praia",
  "🏖️": "praia guarda sun",
  "🏕️": "acampamento barraca",
  "🏠": "house",
  "🏢": "predio escritorio",
  "🏥": "hospital",
  "🏦": "banco",
  "🏫": "escola",
  "🏭": "fabrica industria",
  "🗼": "torre",
  "🗽": "estatua da liberdade",
  "⛲": "fonte chafariz",
  "🌉": "ponte noite",
  "🌃": "cidade noite",
  "🌆": "cidade entardecer",
  "🗿": "moai estatua",
  "🧱": "tijolo parede",
  "💻": "notebook computer laptop",
  "🖥️": "monitor computer pc",
  "⌨️": "teclado",
  "🖱️": "mouse",
  "🖨️": "impressora",
  "💾": "disquete salvar",
  "💿": "cd disco",
  "📱": "celular phone",
  "☎️": "phone fixo",
  "📞": "ligacao phone",
  "🔋": "bateria energia",
  "🔌": "tomada plugue",
  "💡": "ideia lampada",
  "🔦": "lanterna luz",
  "🕯️": "vela",
  "📷": "camera foto",
  "📹": "filmadora video",
  "📺": "tv televisao",
  "📻": "radio",
  "⏰": "despertador alarme hora",
  "⏳": "ampulheta tempo esperando",
  "⌛": "tempo acabou ampulheta",
  "🔍": "lupa procurar busca",
  "🔒": "cadeado trancado seguro",
  "🔓": "cadeado aberto destrancado",
  "🔑": "chave",
  "🔨": "martelo",
  "🪛": "chave de fenda",
  "🔧": "chave inglesa ferramenta",
  "⚙️": "engrenagem configuracao",
  "🧰": "caixa de ferramentas",
  "🧲": "ima",
  "💊": "remedio pilula",
  "💉": "injecao vacina",
  "🧪": "tubo de ensaio experimento",
  "🔬": "microscopio ciencia",
  "🔭": "telescopio",
  "📡": "antena satelite sinal",
  "📌": "alfinete fixar",
  "📎": "clipe anexo",
  "✂️": "tesoura cortar",
  "📝": "anotacao escrever nota",
  "📄": "documento folha",
  "📁": "pasta arquivo",
  "📦": "caixa pacote entrega",
  "📬": "caixa de correio mensagem",
  "✉️": "envelope email carta",
  "💰": "money saco grana",
  "💵": "money nota",
  "💳": "cartao de credito",
  "🛒": "carrinho compras",
  "🎒": "mochila",
  "👕": "camiseta roupa",
  "👟": "tenis sapato",
  "👑": "coroa rei lider",
  "💎": "diamante joia",
  "🛡️": "escudo protecao",
  "⚔️": "espadas batalha luta",
  "🧹": "vassoura limpar",
  "🗑️": "lixeira apagar excluir",
  "🛏️": "cama dormir",
  "🚪": "porta",
  "🪟": "janela",
  "❤️": "heart love",
  "🧡": "heart love",
  "💛": "heart love",
  "💚": "heart love",
  "💙": "heart love",
  "💜": "heart love",
  "🖤": "heart love",
  "🤍": "heart love",
  "💔": "heart love",
  "❣️": "heart love",
  "💕": "dois coracoes love",
  "💖": "heart love",
  "💘": "heart love",
  "💯": "cem nota maxima top",
  "✅": "certo ok feito confirmado",
  "☑️": "marcado caixa feito",
  "❌": "errado nao cancelar",
  "⭕": "circulo certo",
  "❗": "exclamacao atencao",
  "❓": "interrogacao duvida",
  "⚠️": "aviso atencao cuidado",
  "🚫": "proibido bloqueado",
  "🔕": "sem som silencioso mudo",
  "🔔": "sino notificacao",
  "🔇": "mudo sem audio",
  "🔊": "som alto audio",
  "📢": "megafone anuncio aviso",
  "♻️": "reciclar",
  "🔄": "atualizar recarregar sincronizar",
  "➕": "mais adicionar",
  "➖": "menos remover",
  "✖️": "vezes multiplicar",
  "➗": "dividir",
  "🔺": "triangulo vermelho subir",
  "🔻": "triangulo vermelho descer",
  "⏸️": "pausa pausar",
  "▶️": "play tocar iniciar",
  "⏹️": "parar stop",
  "⏭️": "proximo pular",
  "🔀": "aleatorio embaralhar",
  "🔁": "repetir loop",
  "🆕": "novo",
  "🆗": "ok",
  "🆘": "socorro sos ajuda",
  "🔝": "topo cima",
  "💤": "sono dormindo zzz",
  "💥": "explosao boom",
  "💫": "tontura estrelas",
  "🕐": "hora relogio",
  "🇧🇷": "brasil bandeira",
  "🏳️": "bandeira branca rendicao",
  "🏁": "bandeira quadriculada fim chegada"
};
  root.GoLive = root.GoLive || {};
  root.GoLive.emojiKeywordsEn = KEYWORDS;
  if (typeof module !== 'undefined') module.exports = KEYWORDS;
})(typeof window !== 'undefined' ? window : globalThis);

